In [5]:
import pandas as pd
from IPython.display import Audio, display
import soundfile as sf
from pydub import AudioSegment
import numpy as np
import os, gc , time, json
from io import BytesIO
import json
from sklearn.model_selection import train_test_split


AudioPATH= "./audio"
ModelId1="Qwen/Qwen3-ASR-1.7B"
ModelId2="Qwen/Qwen3-ASR-0.6B "

In [6]:
# !pip install pydub

In [7]:
## Convert refvoice  mp3 file to wave file

In [8]:
from pydub import AudioSegment


def convert_mp3_to_wav(src, dst):
    # Convert the MP3 file to a WAV file
    try:
        sound = AudioSegment.from_mp3(src)
        sound.export(dst, format="wav")
        print(f"Successfully converted {src} to {dst}")
    except Exception as e:
        print(f"An error occurred: {e}")

## Load Cantonese dataset, download from huggingface : a cleaned verison from AlienKevin/mixed_cantonese_and_english_speech:
https://huggingface.co/datasets/AlienKevin/mixed_cantonese_and_english_speech

In [9]:
df = pd.read_parquet("train-00000-of-00001.parquet",  engine='pyarrow')

In [10]:
df.columns

Index(['audio', 'sentence', 'topic'], dtype='object')

In [11]:
df

,audio,sentence,topic
0,{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x...,你知唔知今日嘅temperature會落到低至10度，一定要著厚d嘅clothes啊！,天氣
1,{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x...,我check咗天氣app，佢話今日會有thunderstorm，最好唔好去戶外行嘅。,天氣
2,{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x...,飛機已經被grounded喇，因為typhoon signal已經升到No.8嚟啦。,天氣
3,{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x...,周圍都有well-developed霧，嚴重limit我哋嘅visibility，開車嘅時候...,天氣
4,{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x...,Forecast話晚上嘅weather會變得好cold，會降到freezing point，...,天氣
...,...,...,...
14012,{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x...,雖然香港天氣好hot，但我哋可以想下use less air con，改用風扇。,环境
14013,{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x...,Buy local 嘅商品都可以減少carbon footprint，唔再郵寄長途嘅貨品。,环境
14014,{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x...,用solar power同wind power都唔錯，我哋要追求sustainable嘅生活方式。,环境
14015,{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x...,"Reduce, Reuse, Recycle 呢個三R原則喺日常生活中實踐，即係好好嘅典範。",环境
14016,{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x...,我哋凍肉之前，想想下呢個冰箱對global warming有咩影響，係我哋唔可以忽視嘅。,环境

In [12]:
df["audio"][0]

{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x00\x00\x00\x0f\x00\x00\x03Lavf58.76.100\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xf3X\xc0\x00\x00\x00\x00\x00\x00\x00\x00\x00Info\x00\x00\x00\x0f\x00\x00\x00\xe4\x00\x00`\xe4\x00\x05\x07\t\r\x0f\x11\x13\x17\x19\x1b\x1e!#%(+-0257:<?BDFILNPSVX[^`behjlprtvz|~\x82\x84\x86\x88\x8c\x8e\x90\x92\x96\x98\x9a\x9d\xa0\xa2\xa4\xa7\xaa\xac\xaf\xb1\xb4\xb6\xb9\xbc\xbe\xc1\xc3\xc6\xc8\xcb\xcd\xd0\xd2\xd5\xd7\xda\xdd\xdf\xe1\xe4\xe7\xe9\xeb\xef\xf1\xf3\xf5\xf9\xfb\xfd\x00\x00\x00\x00Lavc58.13\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00$\x04\x15\x00\x00\x00\x00\x00\x00`\xe4\xc0zi\x0b\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xf38\xc4\x00\x00\x00\x03H\x00\x00\x00\x00LAME3.100UUUUUUUUUUUUUUUUUUUUULAME3.100UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU\xff\xf38\xc4_\x00\x00\x03H\x00\x00\x00\x00UUUUUUUUUUUUUUUUUUUUUUUUUUUUUULAME3.100UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU\xff\xf38\xc4\xa0\x00\x00\x03H\x00\x00\x00\x00UUUUUUUUUUUUUUUUUUUUUUUUUUUUUULAME3.100UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU\xff\xf38\xc4\xa0\x00\x00\x03H\x00\x00\x00\x00UUUUUUUUUUUUUUUUUUUUUUUUUUUUUULAME3.100UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU\xff\xf38\xc4\xa0\x00\x00\x03H\x00\x00\x00\x00UUUUUUUUUUUUUUUUUUUUUUUUUUUUUULAME3.100UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU\xff\xf38\xc4\xa0\x00\x00\x03H\x00\x00\x00\x00UUUUUUUUUUUUUUUUUUUUUUUUUUUUUULAME3.100UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU\xff\xf38\xc4\xa0\x00\x00\x03H\x00\x00\x00\x00UUUUUUUUUUUUUUUUUUUUUUUUUUUUUULAME3.100UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU\xff\xf38\xc4\xa0\x00\x00\x03H\x00\x00\x00\x00UUUUUUUUUUUUUUUUUUUUUUUUUUUUUULAME3.100UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU\xff\xf38\xc4\xa0\x00\x00\x03H\x00\x00\x00\x00UUUUUUUUUUUUUUUUUUUUUUUUUUUUUULAME3.100UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU\xff\xf38\xc4\xa0\x00\x00\x03H\x00\x00\x00\x00UUUUUUUUUUUUUUUUUUUUUUUUUUUUUULAME3.100UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU\xff\xf38\xc4\xa0\x00\x00\x03H\x00\x00\x00\x00UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUj\xa7\x19\xc0\x01\xa58k\x08\x9b\x10\x80\xb3#g\xcepc\x96|\xdf641A\x0fL\xea#`,\'!\xfd\x00y\x9e\xc8\x1d\xf1\x9bU\x12(\x08\x14 \xe1\xa5H\xd3\x07\xa0s\x8ap\x1cj\xaa\xad\xf0\x04\xb6zM\xff\xf38\xc4\xa0\x00\x00\x03H\x00\x00\x00\x00#\x83\x9f\xa6\n\x95\xa8\xe4\x8d)4L`\xb1\xe0\xe2\x00#\x8e\x1ca\xa0h\x12\x06\xc8=\xd1\xf7\xc0\xee\x1d\xa7\x9cR\x18\xb9\x99X\x9c\xaf\x1e\x84\x84\xec6\xb0\xea\x89:\x08\x8e+\xf3E0\xc1\xc65\n\xcd\xf9\x00x\xd1\xb2g\x18\x11\xc52\x06\x08\r\x02\x91)9\x9dzt\xf71\x9c0s\xf1\x8a\x91\x87a\xf8t\xddz\xff\xf38\xc4\xa0\x00\x00\x03H\x00\x00\x00\x00H\x9b\x10w#\x10\xe4\xcc?\x1b\x7f\xe5\xf1\x88\xc5\x8c\xf5\xce\xc4\x1f\xc7-\xdf\xb5(\x08\x90\x18Zp\xf6\xc0\x84 @\x00\x06\x9cx\x80@\x01\r\x88\xe6!\x19\xe3\x0f\'\xa4\x02&\xe0\x86i\x88:|\xf0\xb4\xcfL\x990\x18\xf3\xc0d\xd7\x12M6\xdea\x08\x83\x08f9\xee\xef\xd0\x80\t\x9aW\xcfB\xbc\x08\x89\xa2\'\x0b\xff\xf38\xc4\xff"\xf9 y\x98\xd6t|@\x80\x02\x00\x04\x15?\xaf\xd7wO\xa6\x88\x85\xfa\x15wr\xfa\xfcA\x00n\xe7\xd0\xe2\xcez\x80\x12\x8d\xc0\xca+\xa7\xd4\xa4\xb42\xb6\xddw\xc8\x87\xa8i\xbc\xe2\xf5\x80\x12\x90H\xf3\xdc\x99#"R"\xb6\x7fD\x8a\xc2\xf0\xc7\xe4\xce\xa2\xa76`B(\x0b)\x05\xa1\x9b0\xc8aw\xb2\xac\xad\x95\x10^I\x9a\xf1\x16\x8b\xff\xf38\xc4\xd2#\xa3=\xfc\x04\xc1\x875T\xea8\xaa5l\xb0\xb4Q$\x9c*\xa7\xfa\xb970\xd9\x88\xa7\xcf\xcb\nl\x8bK\x9d\x881\x8ck\xee\xdf\xe5]{\xb8\x82x}cE4\xb3\xc3\xcd\xcd3]\xbd\xb2\xf1\xe1\x16\xf5\xa8x9\x992\xef,\xb2\xda\x81\x15\x04\xb3eL\x10\xc1\xa8\x160\x03\x81\xc3\xe0\xd4\x91C\xc1\x1c\xf3\xc9g\xae\x0fERyM\\Y\xff\xf38\xc4\xa2 \xc36 \xb6\x1b\xcc\x11k(\x1eM\xf6\xdb\x05\xcf\x1c@u\xe4MBh\xb0\xae\xf3\xabaX[\xd6E&\nG\x90\xc2L<\xd3zM\xabJ\xab\t\x99\xb2\xc2{a?\xf0\xe8\xd2\xfb\xb92E\xdcc[\x13Jy\xfb\xd0\xc41t\xac\x08 d\xb6 D\x06\x94^\xb4tB:b\x17X<:fa\x94\xaa\xf3\xf2\x9a\x13\x99\x03Tc&\xdc\xff\xf38\xc4~"\x93B\x18\xa6a\x87l\xc2"Qq\x10\xa2\x81\xba\x10@\x94\x05\xaa\xdd\xec\xe2x+\x89\xc3x8\xc4\x08\rc@\x98\xa1N%\xf2\x03\x82\x95\x91\rW\x1f\x91\\\x10\x84\xb9\x00eo|\xc71\xa9Z\x9c$\x08\xa2\x85\x94,\x0c\xa8\xbe\x90\x88\xc7\x02\xb8\x88\x16.\x8dpx\x94\x9d\x13z\xbb!\x07R^t\xc8\x94D\x14\x9ad\x88\xc5\xd1\xa3\xe7E\xff\xf38\xc4R$k"\x10\x00zM\r\xe2CA0\x13b\xadg\x16F\x0f\xb3F\x17V\x96\x14\x8d\xc2i\x9aR\x8d~\xe7vcN\xb7\xfb]\xd2\xed~\xf3\xbe=\xdd<>\xed\x95y\x95\x9b\xef\xd3s\x9bi\xe3b\x9f\xeb\xe6\xea\xdd4\x9f\xf46|_=|\x17\xc1S\x81p\x98\xf5I\x02\nP! \xa0\xe4\x01A\\!\x84\x99\xa0\xb0\n0\rG\x871\x15\xff\xf38\xc4\x1f\x1a\x81\xf6\x1c\x00\x0b\x0c\x0c\xeb\xb1\xe7r\x1a\xacF\xd0\x05z4\n\xce\x07\x805\xca\x8d;&\xd2\xe4\xb9\xc4a3N\x971s\xb5po\x8ey\xf1\x89\xc6\x1d,\xb7\xc6w\xd7\xc6\xda\xc2\xef\xe56$ha\xe4]=<@\x89\x84\xdc\x9d\x80\x0b\xdc\xe7[\xbc%~\xd2qr\x02\xabZ>\xb7\xb2\xc7\x95\xb0\x0b\x85\x05R\xb0~\x04a\xa6p\xc4\xb2*\xff\xf38\xc4\x14\x17\x99\x8a$\x04a\x86u\xf7I\x85\xda\xcc+\xd5\x1cj^\xda\xef\x85\xcc\xa0.\xec\xa1\x18\x82\x9f\x92\xc0H_M\x8c\xf7f\xfedFf\x86\xac\x94W$)\xfc\x81\x9e\xde\xaem\x1dA\xd6\xef\xbaM\xedKBZ\xd5\xdb\xf6\xfb\xf1\x8c\xccz\xe3|\xd2\xcb\xe0\x87z}\x91\xc9\xb4J\xf7\xbc\xc5\xcd\x92\x10\x05C\x83a\xa2bfN\xa8\x84B$\xa4T\xff\xf38\xc4\x14\x16\x81\x82(\x02I\x86\xc8r\x85\xe9\n\xd2\xc8\xcd\x96J\xaa\xd6hE\xa5Y\x18\x98\xc8HA\xc9\xc4\x82\\\x95\x98\xe2\xab\x91v\x99Bj\x18\x973UX\xc0\x81\xd0\\\xea \xe0\t{\x92\xa05\x84\x83m"{\xa1\xdc\xfck\x93.W\x9bz\xaem\xd7\xa9\xcb\x93F\xbf}Tb`\xc5G\x94\x97\xda\x01\xd2\xcc\xc4N|\xc9#"\x85\x92!\x08\x08\xff\xf38\xc4\x19\x19*r \x02zFtT]\xc2\'\x112\xe8t\xdb\xb5\x84\xa0\x92\x03*\xe1\x83<\x14\xc1\xd5\x85\xa3\x0b~\x883d2@\x1d\xb2738NJd\xab\xd70\xc7\x87\xc8\xe9\xa1\x92o\xfe\xb4\xd3\x9d\xd8\xbd>\xcc\xf9\xff\xc7\x87\xf7\\b\x1a\xeek\x11\xc9\xa93\xf6\x99I\x8e\xf0\xad\x80\x05b\xbd\xb5\xd7\x85\xc0pH8Bia\x8b\x85\xbd\x89\x9a\xff\xf38\xc4\x13\x14\xb1N)Da\x86\x88\x15\xab"Z"Q\x81p@\xbd\x0b\xc6\xa4F&\xd7\xc8I\x99\x912\xe7\xf0\xe4\xa7L\xbeg\x95\xf1\x05\x92e\x89*\x91\xadC\\\xd7T*\xa7\x8b\xadb\xd6I\xce\xf44\xe5\xbb\xcd\x18\xc6.\x87\xfb\xea\xbd\xcb\x185UyH\xdd\x86\x0c\x1b1I\x07\x89\xf0\x0e\x88\x03 l\x86\xda\xe14y\x0c/\x04\x19\xb9\xc8\xa7\xb1\xbd\xff\xf38\xc4\x1f\x11\xf0\xd2(\x02I\x86\x8cjbd\x17 \x006\xf3M\x07\x9c\x9b\xc0!\xf1\xa6\x83\xcfA\x91\xa1\xba\x96\xe6c\xd0XZ\xda\x15\xbf\xdb*\x9dJ\xdb\xe9\xdd\xec\xdeU\xdb\xff\x1a\x18\x01\x00\x8a\x120D\xb1B\xaa\x0e.J@(@_\xe5\x18\xf8\x9c\xf7\xdc\xf2\x13T>\x92\x7fw\xb2\x1a)\x8b\x13\x81\x012\x00\x84\x1c\x03\x94\x04\xc2!\xf9\xb70\xd8\xf0\xff\xf38\xc46\x12\xf0\xee(\x00HM \xa9\xe2"\x01V\x8c@I\x8f\xa9\t\xe2\x95;\xfb6\xf6k\xfa\x13\xf7\xb1\xa4\x00\x00&\x9aJ\xc3o$">\x08\x1fA\xb6\xba\xc1\xfao\xb1\xa4\x10\xe4w,\xadt\xf7\xba\xde\xf49}\x9fv/\xbd]\xfc\x83\xff\xc9\xa40\x8e\xf7\xad\xce\xf2\xca\xa0\x00\x91d\xe2\x96\xec\x05\xe4\xe3\x0e\x85VU\xc8\xdc\xfaT\xabzk\xc7\xb3\xff\xf38\xc4I\x0cX\x02N6\x08\xc6\x04\xe6\xa9Z~-\xf7\x95\xff\t\'\xf4\xff\xed\xfb\xbbo\xe9\xd2\x01\xc0\x01\xa6\xe0\x8fB\x12\xe0\xe1\\0P\x15\x0b\xa02\x94\x03\xa5\xd4\xc1\x82\xee\x14\xb0~\xba\xde\x9a\xe8\xa9\x9e\xa2U\xe4b\xf7+\xee\xb5\x0e\xdc\xbc\x8fWs=\xc3\xbe\xd5v>\x97"\x80\x00\xb5\x06\xa0\x99B\xad0vI4\xab\xf08\x08\x00\xce\x16\x0c\x86l\xff\xf38\xc4v\n\x80"Z>\x08F\x00*V\x1fJ\xc3%B\xb4\x86\xd2\x01\x00\xa8\x99\xb84\x11\tH3r\x1c\xd5.\xf3`\x11\xbe_\xad\xcf\xfa\x91\xa124`n\xb7\x16\xa7-\xdbLKY=\xd6\x90\xb0\x05\x89HFtJ\xa0\xa9\x19\x01^e\x00\xbc_\x8d0\x91\xcad\x15\x8e\xa2\xa6\xa2U\xeb[\x0e\xf7\x80\xe9\xa0\xac(Yg\xfcoS\xad\x1a\xab\x0f!\xff\xf38\xc4\xab\rp6=N\x08D\x00\x9d(\xfb]\xdd\x16\xc5\xab\xd2&pT\xdaY\x18rLx\x15\xee\xb1\xd7\x8cT\xe5\x05\xcb\xfa\xa05*\xa8\xd2\xcd\x14\x1ad\xd1\x86Rq\x16\xae\x9d\xa5\x1f@\xb2\xa4a@f\x924\xda\xa3\r\xa6,.(p\x82b\xaaI9.\xa0\xa1\xd3:\xa9;\x0c\xe4\xa6@^n]\x12\x12\xa9!a@\xc2F\x11\xb7\xe9\x94\x94\x94\xff\xf38\xc4\xd4\x10\xb8B5L\x08\xd2\x00Y\xbe\x96;Y\x8a\x8f\xdc\xa3\xea\xe9\xdcT\xcd\x16V\xe8\xad\x82\xfa\xfc\x9a9\x07Z\x93o_\x8e\xeb\xf1\xfb~\x0e\xda\x93~\x9fP\xbf\xfc\xfd\xf7\x9f\xf7\xf1\x94\xb66\xbfj\x81\xbc\xf0\xf0\xa3\xe5E\xc9L\x88\xcah\x82e\x13]\x15\x82M\x02\x990|\x9c\x96 Z6^\x16$\x82\xc8\xc6\xce\x84\x9dh[\xcbH\x80>\x17\xff\xf38\xc4\xf0\x16y\x9e(\x04I\x84\x9c\x99#~\xab\x86\x99\x02\xa1\xc9\xba%\xce\xfb\x14\xa3\xa3\x1f\xb5v\xa7\xeb\x8c\x18\x81\xb6\x1a5\xf6\xb7\xfbm~\x9bk\xb7R\xccw\xf1MN\x87lkS3y\x90\xf8\x9b\xa9\xbeU\x80dK\xc8d3\xc1\xd45\xa9=\xc0\x94\xcc\x94\xd1\'\x92\x0f\xf0\x8aR\x84\xd4\x14\x91\x87\x1b\xd7\xee\xb4\xc2\xdd\xbe\xee}\x84P\xd6\xe41\xa7\xff\xf38\xc4\xf5\x1aQF \x02\x0b\x12\x05>\xea\xf8\x893&\x89\x87\x07\x9228\xa4Q\xa4p"G\xb9\xe7\x14-\'\xc6\xbd\r\xff\x1a\xbe/\xbd\xa4\x18m\xed&\x86\xb8\xe1\xa5f\x95\xb5\xf6\xe9\xc1SR2U\xa9\x04\x83\x04\xd0\x0eD\x83\x8aQ\xc3\x83?~8\xcd\xf6\xd1\x1fD\xe4\x07\x17),\xa1\x99\x05\x19\x0f\'R\x97\x1b\x81N\xa3\xc7\xf0\xb3Y\xe1,\x8e\xf3\xff\xf38\xc4\xea\x18\t\x92,\xa4I\x84\xd1\x94\x84Z&"MPZ\x06$\x16\xb3\xe56\xbdw?|\x1d8\xc1\x88\xb2\x86\x90\x88\xb5\xb7\x11\x1cL^\x87N47\x16lP\xc3A2\t\x9d6*a:\xf6\xe9\x1c\x04\xc5\xbf\xa2\xb0\xfcG\x14A\xee\x1a\xaf8<1@,\xc6c\x9cp\xfd\x8aIR&q\xa18\x01\x12n\x94R\xea\x93|\x83~\x9cV2J\xf0\xff\xf38\xc4\xe8\x14\xd1\x12(\xa4\x0b\x0c\x08 n\x96\xbd\xfb;\xde=dGw\xcd)\xb2\xfb\xc1?\xab\x86\xae\x1eX2T\xa3\na\'\xa4\x12\x8b\xa8q\xb1\xee\x8a\'\xb6b\xd5\x94Qg!\x1a?\xfaU\x80\x98\x19e\x81aX\xf8\x04&*&"]M0\xf7c\xaaf\x9d\x01\xe5\xd2\xc9\xa4\xb2\xad\x16\xe1\x82\x94v\xedLp\xfdf\x0eA\xb7Dh9P\xb1`\xff\xf38\xc4\xf3\x1aB\n\x18\x00a\x87,8\x10\x19@q\xcd\t\xa8\\\x9d\xe2\x83\xaf\x97K;\x84w+\xb3x\xb9\xe7\xc4\x8c6\x18-f\xff\x1a\xd4\xff>y\x89vB\x97\xb1 pR\xd9p<\x0b)\xc4\xa2=0\xc5\xc4\xa0`\x96\xda\x80\x9c\xeas\x0f\xb7e\x85\x8b&\xe4\x02h\xd4\x98\x98\xef\x01j\x07,\xe3\xdb\x02_\xc60\x0c\x19\x89\xa4\x83cZOA\xad\xff\xf38\xc4\xe9\x16\x91r \x00{\x0cPE8J\xe8\x992C\xdc!\x98\xa5H\xdb09\x937\x84\xea\xb2\xcd\x92>\xfe{&\xd47\xfd\xff\xe8w\x16\xd1\xc3\xaf\x7f\xb7\xfep\xbf\x81\xae{\xa9\xb0\xe5\x14\xff2\xea!\xd9\x0c\xac\x01\x82\xa3\xe5m\x98\x05\xc9\x88\xe9\x02\x10\xa2\x87\xb7f\x18J\x0fz\xe1\xed2S\xacr}9I2S\x12L\x99\xa7w\x85\xe4hS\xff\xf38\xc4\xed\x14\xc1\x06(\xa4\nF\x1c\x86\x0e"\xfd\xaamXC\x0b"\x02\x94\xd2\xa3\x9c"hd\xb1C\x18R+a\x16y\xfc3~\x91\xa6\x93\x80\xe3\xdet\xf3a\xd4\x00\xd4/-1\xdc\xfb^\x10C\x9a~\x87\xd9\'B\x81\x86\x84\x00:\x04\xce\xc6\xa1$\x98\xcf\x1d\xc7\xa5S\xb6#)0l\x82!\x8e\x92\xfa\xf5G\xe8})\x1d-\x99\x10-w\xb3\x9f\x93\xff\xf38\xc4\xf9\x1aa\xa2\x1c\x02I\x87\tL\x8d\xe5\xac\xd9\xfdQ\x8d\xf2\xe9\xebt\xa0|{\xd8X\xc0\xb1\xd9\x88\t\xc5\x1c(8\xeb\x15\x16Z\x8a\x11}uP\xe4\xbfC\xa8\xeb\xf6C\xb7\x7f[\x9aJ\xfej\xb5[a\xd3-\xab t z\xee*G\x88\x1b0\xb1\xc5E0;V?B\x92\xb6F\xb7\xb5\x1e\xea\xb12\x10\x13\tH\xafb\x8c\xc2\xcf6\xe4\xb3\x17\xff\xf38\xc4\xee\x19\xaa\x02\x1c\x02bF\x98\x9e\xa8\x96\x05s%\xf3\x0e\x1d,2U\xe7\xeeI\xb9\xaf\x0ci\x15\xab\x8eK\xd7w|\xad\x96\xd8,R2\x8f{\x8f\x91\xd3e\xd9\x87\x95JF\x17.\xe7\x98\xece*\x13v9\xe85e\xca\x99\xb1\x0b\x16X\xa1V\x8b"LAME3.100\xaa\x88\x00\ni$\x01\x9e@\x066\xbc\x0c\xa1W\x87X\xf1Yc\xff\xf38\xc4\xe6\x15\xb1.$\x00\x03\x0c\x1c\xc0[\xf1C\xcb\xe3\x9d`\xc8\xa4{;h\xff\xa8\xa7\xf4\xa7W}\xab\xdb\xf4;\xbb\xfa\xb1\xf4)U\x80\x06c\xe3]\xf2\xf1w\x1f\xa1\xb2.C\x11[T[Z\xf95\x7f\x1f\xd1\xe4#\x85\xe5\xa3H\x170\xfdkul\xfb\x16\x1b\xcdX1\nx\xb0\x1e\x15\x11\x10\x04a\xe9\x9b\x92\x84\xa5\xa35\xf5ir\xfd\xb3<V\xcc\xff\xf38\xc4\xee\x1cq\xc2\x1c\x00\xc3\xcc|0\xe0\x88\xcc\x8f\rciZ~_\xbf\xcb\x90\x865\x82\x88\xa5!0\x13@\xa6\x03\x94,\xdd\xc7\x14\xd1\xd9!\xaf3I\xa9\xe4\x15\x9d\x81\xa8\xbf\xcc\xdc\xc8\x11\xa9T\x88h\xb5\x87\x96\xb3\x02e\x94H%\n\xe0\xac\x8e\xab\xeb\x99Dz\xa2\xad\x14\xf7\x88\x82JJo\x9e\xb5\x95\x85\xdd\xc4N!\xa6c{\xbb\x9b\x9d*\x01J\xff\xf38\xc4\xd1\x0c\x18:I\xf6\tF\x04\xf3.\xc2/%\x04|2c$L\x9a|\x9e\xaa\x84\xb9\x94\xf0\x9fO"\xeeUZ4T#\xc9Yc\xb1F\xd53\x91\x83\xc5<\xe8\xa4\x05|\x06\xbd\xb6\x1a\'\x1e@\xa5E\x9cKU\xa2eE\x0b\xa1E\xc0\xc72(\xe4\xc5\x9a\x87@T\x01\xab\x1eZ\xe8Bx\x14\x13\xc0\xdc.\xe5Ah\\\xe16\x90\x85k1\x04M\xff\xf38\xc4\xff\x1aB\n%D{\x06XGRD\x87\x16;\xc9\xa3\xee\x9e\x91\xe1\xdfi\xc6\x82\x80\x01!%!\x82\xe6]\x151\xfc\n\xee\xf6\x89\xfeq\xaaG\x99\x8d\xb9@\xa7L\x16\r?^:\x0e\x9f\x8d(\x11\x02$-2,m\xae\xba\xf0\xf9\xc0\xb9\xff\xa00\xf0@\x10\x18\xe36\x7f\xa2\xa0\x89\x03\xff`\x9e\x0f\xbd\xfdm\xa3"C\xee\x0c\x06\x88\xa6Q1\xb9\xff\xf38\xc4\xf5\x1ab\xb6 \xa4a\x86\xb9\x02\xa0\xa2\xc2HC\x98\xd3!\x07L8bT&\xde\x89\xcaJ5\xb8\xc1\x07\x0e6\x89\x8d\xcc8\xc3%7\t_\xc8[\xb3\xf1\x1d\x87\x1a\x92V<p\xccq\xff\xa7\x9b\x97N\xcb\xf0\xa9\xbc\xf3\xa7\x951\x03\x14{/+1\x05\x0cr,\x99`\xc3\x90\xd5_\xca\xdeJga\xc8\x873\xdcn_D\xe5\xca%\xf1\xe7\x95\x93\xff\xf38\xc4\xea\x1fqR<\x14f\x1e,I\xa5\x8aV\xacOk\x87\x05\x18@sY\xdb\xa7\xff\xfe\x84c\x9ee;#\'\xea\x7f\xff\xff\xff\xff\xf9\xd8 \x1d3\x1c8\xc4Nqu\xff\xd5\x08\xb4p\r\xba\x81r\x0e\xf0\xe6\xa4(\xca\x08\x19\x0bZ\xe0\xe0\xa6\x80\xcc\xa2X\xe0\xa3(\xd43\xb0\xf3\xd20Y\xb8\x8d\xd12-\xf1\xea\xd4O\x95\xec\xd9-\xb0&\xf7P\xbc\xff\xf38\xc4\xcb%"\xf2\\\x00\xd6J\xd8\x8bW\x1b\xb2/]8\xedB\x9a"\x8e\x0e\xe49AJd\x1c\xb0\x0e!\xde8\xe7N\x1f\x87X\xe3c\x1c\xa8\xe3qa\xd3*\xc1\xc8\xf5\xbfT\xd5\xa0\xe6\xf7=\xdf<\x81\xf7m=\x8eOt\x88\x16\x15\n\x1c\x05\x94\x19\xcc\xd0\x0e\x83\x08\xd6\xbf\xdf\xff\xfe\x9f\xfeq\x04\xa0\xc2A\x86]J \x02d?\xf5\x1f\x0eU\x7f\xd7\xff\xf38\xc4\x95"\xaa\xf6h\x00\xcb\xc4\xf8h\x81a\x80\xbe\x11*\xcd\xe1\x91\n`\xe4) %l1\x07r\xe1\xfc\x86\x90\xc7\x8f\x08\xc1!H\x95\x1b\xb7&\x17\xf9\xa3+\xef\xbcS\xe7v\xce-\x8c\xc1\xb6\x1bU\xb4H\xe5<\xd3v&\xe5\x12\xbdHk!ie\x82N"\xa2j\x9e\x18\xe6q`!\xeb\xb3I\x1e\xa9\x8b\xb9\xb5\x98+w\xac\xee\xe6cfJI\x8a\xff\xf38\xc4i$B\xfal\xe4\xcb\xca\xdc\n\xa9\xcaEr\xfc\xc1\x864\xe0$1\x18<\x9a"3,\xb62#:\x1b3\xde\xe7:\x8er\'\xa3\x7f\xfb\xab,`\xc28\xe4j \x1b\x89n\x0f\xff\xb8\x95B\xc3\xe9\xdfg\x08\x01\x04\rDH\\\xbd\x0cP4X\x07ZtU\xbd\xb3\x0f\xda>iy\xb1\r\x95,\xa8\x8a\xf6h\x1f9\xd6\xe2g8\xbe~+\x01\xff\xff\xf38\xc47 \x9b\x16x\xee\xd3\xc4\xdd\xf9\xcc6:\xf9\xdf\xc5\xbd\xe9f\xb8G\xc9\xbc9\x0bzJ\x13\xe7$9\x9a\xcb\xa7\xef!\xdb\x18an\xad#EC\xae\xc37\xe8\x86\xa2\xea\x9fN\xd6G@\xe2\x9c\xa9\xff\xf5\xa7\xef\x94K\xd4\x85\xe1\x8e\xdd:\x82\xabQ\xd9\xc38\x94\xa74<\x0e\x1a\xaa\xb5\x07\x88\x12\xb7\x00\xff\xfd:\x8a\x14\xd6f\x9c\x11D\xa2\xa1z\x8f\xff\xf38\xc4\x13\x19\xb9\x92p^\xc3\x10p\xe1w\x8c\x9e|lV\xc1\xa5\x86\x92\xa59r\xd2\x95IA\xd9\x0fm\xf7\xdc\xf1?\xc3\x076\xb6t\xad(:-|0\xb0|\xc2\xc1\xd0\xfc\xee*\xa3%\x04bG1b\xafL\xe2\xa2\x8c\xa5,*M\xe3\x14\xf3\x1c\x1a\n\xd8\x06ZY\x886\xe3\x96wF\xb7T\x8c4"y\xec&\x08\x0b\x02\xff\xce\x81\xe1e\xa3\x04M\xff\xf38\xc4\x0b\x17\x1bB\x84\xf4(P\xdcT\xf3 \xf7Q\xafF4@H\xcff?\x92\xf2\x06O\xc1\xccn\xe0\xef\xa3\xc1\xc6%\xff{E\x17D\xaf\xff\xaf\xffw\x0e\x00P\xc34-\xd8\xa39\xfe\x05\xea^\xe9\xf7yx\xa7,\xfb\xcb>\xde\xf7\xb4dJ\xea]\xff\x84}\xed\xdfw \xc9\x10\x00\x0eu\x10\xb6\xf6(\x95\xcd%$\x01\x80{\x88bSz\x87\x18\xe4\xff\xf38\xc4\r\x173F\x88\x00\x03\xca\x10FmIx\xb8}\xacW\xa36\xabU\xff\xef\xd5\x0c\xf4S\x1c\x8cw\x89\x9ci\xc0A\xc4A\xa7f\xba\xbb\x91\x19\x9bT?\xf7\xaf\xfc\x9d7!\x0c\xaeId\x7fMr\x9ad/\xdc\xa47\xdb*%\x8e\xd4\xd1\x0bg3\x89\x0f\xeaa#\x08\x88\x05:-D\x86\x87E\x9d\x12E\xb3\xd7T\xd8\'\xff\xe7R\x9c\xb0\x01\xbf\xf8\xff\xf38\xc4\x0f\x17y\x86\xa2Z\xc9_\x0c\x0e\x06\x00\xcd(\xefU\x8d\x1b\xe3\x01\xec\xc7\xb0\x05}\xfc\x17\x16\xd7\xd5\xb1O>\xd3\xec\x8b\x11\xa58\x11\xe8\x8c\x96\'6[u\x13\x17\xd9\xf7\x13\x89^\xfa\x1b\x1e\x91\x05\xb4\x9f\x0cH\xd5\xc6(\xae\xa4H\x9a\x87\xe3\x9f\x84\xfd.\x14d\x87\xfe\x07\xc3\xbf\xff\xfe\xe5\xe4\xdc\r\xf5Y\x95\xe3V\xe4\xb6\x8f\xa8\xf0\'\x87`#@\xff\xf38\xc4\x10\x14\xe9\xa6\xe6~\x83\xca^4?\xfe\x84\x10\x06\x98\x11U\xcc\x0cf\x10\x00Ak\x83\xadz\xa9\xc7\xdaQ\x89\xae\xceHb\x95D\x17\x11\xa9\x1e\x12\x17\x86\xf7\xe9\xbd\xfa\xaa\xbf\xb6o:\xa8\x17\xb2!\x0e\xcfF\xaa~$+\xfe+@k\xff\xa7\xff\x89u\xffU\x00\x89%\xd9\x90(\x00\x7fb\t\xa0D\xd7V\xfd\x8a\xee\xdaU\xa7\x13k\xaf\xa4\x880\xc7\xff\xf38\xc4\x1b\x14 \xe6\xbd\xbe\x06\x18\x18%\x1d\x9f\xf8> \xee\x1b\t\x052\xcd\xdbmX\x80\x0e\x10G\xb1\xc4{\x1d\xd7\x99\x8a\x0e\x8b\x87\x953B4h\xc0\xfe\x08\xa8\x97\x0b\xb1\xd4-\x10\x1b\x16r\x1d\xbfO\xfc5Q\xb5\x92\xff\xf5B\x95as2\x18)/\r-\x1e\xd0f\x04\xc9\x8c\x91i\xc9\xbdH\xca\x85\x1e\xceh\x13\xb8\xa60\x92*\xd8\x99~\xf5N\x95\xff\xf38\xc4)\x14Q^\xa4\x10\xc3\xca|;\x1e^6$\xc6\xfa\xb3VN\xae\x89@\xa7\rBE\xb2y\x11[\x1e\xb46U0)\xdap\xf8\xb7\x9f\xc6\x04e\xa6\xca\x8c|\xf2\x151)\xc9%\x1f\xfc\x16\x89\xf4\x80C\x00[\x00\xb9T\x841G\x82uY\x96\xdc\x9a\x009fJ2\xb3v\xfbhN\x83"\xa5%\x9c\xef\xf4\xd1\xd5\xcb\r\xd4\x94\xee\xf5r\x00_\x05\xff\xf38\xc46\x151\xa2\xbc>x\xd4\x92\x13\xec\xeakv\xe8V\xb3\xf3T\xcb\x13Ul\x90\x95\xddl\x9d;\xec\xb2\x8a\x9a\xd7J\xd7Y\xa8zM\x00}\xfc\xb6\xad\xb4\x0f\xfd\xe1\xc13\x85\x19~P\xa1\xd0\xc8\xe8\xc1\t!\x0b\xc30\xc5\x12\xa4Nwc\xe5Wm\xa6\xa3\xb2\xa5V4q\x8c$\xdd7\xc4\xa3\xa1\xdd\x84\x85\x04\xc4\x89DS<\xc7\x02\xff\xfe\x89u<\xff\xf38\xc4@\x151\xf6\xc1\x9ey\x8av\xd2\xa5\xba\\\xa50\x86\xa7\x107\xef\xb1"\xe9\xf4\xc6[MV\xd2EP%crI%\xaaA\x99L\xaa&\x06\x83(\x8f\xccm\xe5\xd2h\xea|\xce+\x86\xad\x10\x08\xf1s\x19\x10\x82\xb3\xa7\xe9\xdf\x85{\x10^om\xcbC6\xf8|R\xa4y\x19\x88\r9\x9b\x81\xf6@\x81\ts\x89\xd3>L\xbd\xc8\x10\x0c.*\x7f\xff\xf38\xc4J\x151J\xca^\x0b\x06\x1a\xfc\xff\x86>\x99tX|>\x85\xa1\x04a\xf7\xe3\xa08\x13\x80a\x80\xd5\x1a\xe4U\'\xc6\xba\x83\x81\xe3=i}:]J:[\x9e\xfdm\xa1\x02\x00\x11d#?\x91\x08\xa7\xa8\xb9\x0e\xfa\xe4\xf27\xff\xff\xde\x8c\x8a\xe4!\x0f\xe4\x08B\x0b\x06\x06\x19\x82\t\xfadBY\xfb\x0e\xbf\x9dI\xa3\x0e\x92)\x8eL\xceQ\x85\x89\xff\xf38\xc4T\x1ds>\xa4\xca@\x999L\xd4\xab8<\xa9\xfa\xfb\xdda\x81\xc1\xe2\xf5\x8c,&<T,1NC\x02e\xb3\x85\x0cr\xc3\x85\xa6\x7f\x1d\xff\xec\xfc:\x14\x11I\x00\x06c\xb8\x0c\x07\x84\x8a\xc5dO\xe4\x82\xce\xe7\xbcR\xe64\xc6\xf7\xd7v9\x0fK\xb9Da\xf2\xe6I\n@\x89g\x1c\x1e\x16\x1ePH0\x1e\x16\x1b\x84cq\xb12\x03B\\\xff\xf38\xc4= ;:\xac\x00y\xcc\xfc\xdc\xc3\xab\x9c8,c\xcb?\xdf\xfd\x7f\x8c\xaa\xdd\x84B\xc0\x82\x1d(\x03\xa7%\x178\xf8\xdaEB\x87\x01\x84[\xd5\xe4\xaf\xd8\xadt{\x1aQ\xa4H\xca]\x19\xc6\xd4h\x90)\x19\x07C\x928Z\xbc\x96\x85\x1d\x1a\xf2\xd5\'\\\x04\xff\xe0\x06g\xff\xfb\xd4\xe4\xcd\xc83m\x06\xdc\xbe\xdb\xdaH\t\xdb\x90\xff\xec.\x17\xba\xff\xf38\xc4\x1b\x15i\x92\xc1\x92\xc1R\xf0\x9a]H\xb9\xdc\x80A\xc8\xe19\x15\x80\x02u\x7f\xf5{\xfa:+p\xe8\x895S\xe2E\x9f \x0c\x0c \xf4\x17S>\xf63\xdd\x88\x85\x8eFjI\xdc\x06}Y\x04\xb1\xa6\xcb/\xf5\x7fw\xffM\x11\x8f\x15^&\xe2\xa4\x9c\x0f\xf4\x80l\xdfl\x02\xe1\xb8\xf4d\x95M\xcc\x8f R\x04\xde\xe9UD1\x93\xba\xd4\xc3\x96\xff\xf38\xc4$\x14a\x86\xea~^\x06\xc8\xfd\xdb\xad3\x19\x97\xe9B\x80>\xef3\xdbG\xff\x85\xea\x88L\x7f\xd2\x06=(\xc2\x1d\xf5B\xff\xf9\xc1\x19<\xff\xe1\x00\\Z\xdf\xf7\xff\xff\xd68\x06\xe5\r\r3\xf8\xc2\r\xba?\xf8\xa9\xa8\xfeg\xec\x0c\xa38G\xc7\xe1\xd6\xae\x15\x8a&{\xca\xa3\x8b\xff\x94w\xc4\xcf\xc2\x96\x9f\xe2\x99k\xdf\xb2\xdf\xff\xa5\xa4\xa2@!\xff\xf38\xc41\x17Z\xea\xee>zE\x0e\xbbG\xa3\x06}\x8a\x19\x1f\x86N\xdd\xb5k\xd0\xc56\x18\xff2\x95\xbf\xff\xff\xf3\x1aQ\x9d*\x99T\x8f\xff7\xfe\xdf\xff\xff\xf5\x048\x87\x8ab2\n(E\xac\xa5,\xb2\x8f\xf5\x00`\x94}\xe0\x9c\x08\xa4\xc2\xd4\xd4,\xdfK\xcbbgD~\x89{\xdc\x85\xcc\xd9\x92\xbe\x7f\xca\xe6emR\x98!\x99\xcb\xe8\tN\x97\xfd\xff\xf38\xc42\x14Y\xfa\xe1\x9eX\xc5\x16e#aU\nU\xb6\xff\xef\xdb\xfd5\xfb\x86:\xe1qp\xf0\xa7\x13\x8b\x89\xfa\xc3\xff\xfeJ{\xfa\xc3u\x80"\x9b\x88\xa7\x1c\x90~N\xb6\xb6\xac\x07\x07BMb*\x88E\xc1Z\xb2\xa3\x0bT\xc9`\xd3\xad\x87,*\x05=\x91\x04\xa4r\x11\xc1z+zd,\x1bHj\n`\xce^\xa6\xe6\x98j|1\x8b\x9d_\xdb\xff\xf38\xc4?"\xda\x86\xdd\xbef\x06\x9b\x98k\x17\xa8\x1c\x16\xc1/\x8a<\xb7a\xc9Y\xd5/\xfc\xfd.r\xc2\xa7\xa0W\xcf\xa0n\x06NeH\x8d\xe0\x87\xe8\xb4$\xd1E\xc2\xcb\x12\x7f\xc7\xfe\x9afON|\xa11@\x00BE\xa3Y\x13;\x82*\xf1\xe34\xe7%\x15}\xf4\xfe?\xef\xc6$\xcf\x8a\xc4\x02\x01\x9b\xa97\x1f\xe1\x8e\xce\x8eq\t\x9b\x06\x1d\xdd\xcd\xff\xf38\xc4\x12\x15\x08\xc2\xea^3\xf0\x88\xea\x84\xdf\x1b\xe8\xdd\xd19<{\xa6\x03\x9d\xd7m\xceyR\xe5\x88+\xd68\x9d)\xd4,\xd0I\x8bl\xe5_}h\xee\xce\xcc\x80\x9c\xe3_\xde\xdb\'\x05\x80B\xd0=hQs 2\xe8R\x1f\xff\xd5W\xff\xff)\xcb\xc9\xd5\xad @)e\xb7J.1/\xfd\x84\xea\x92\r\xfe]H\xf0\xcbQ\xeb\x9e\xf8\x96L\xb9\xfb\xff\xf38\xc4\x1c\x14\xb1\x9e\xf2>HG"X>g\xd4\xb7\xc6\xbe\x7fU\xbb\xb6\xd5J\xa9F>\xffK\xd9\xaf\x0ci\x19\x8c\xfe|n\xc1F\xb0V\x0b\x11[\x962V%\xa4\x95\x120\xeb\x8e\x9eQ\xe9\xda\x9f\xff>\x8eX\xb0u6e[iw\x16\x85,\xf9\xd2k]vM\xb7\xc9\xea\xb7K\x93+\x11[\xd6b\xf3\xfen\x93C\'\xad\x14\xa8\x86z\x95\xber\xa0\xff\xf38\xc4(\x142\xea\xe1\x9e\x03\xc4\x1e6;\xb1\x94\xac\xf4D\xd2\xfd\x9f\xe8\x86:\x985\x1d\xae\xc5\x7f\x7f\xec\x87\xff\xa8\xca\xd5\xea\xca\x8e\xdfO\xff\xff\xff\xfe\xad\xfa\x89\x12\xff\xbd\x11\xa0\x80

In [13]:
df["topic"].unique()

array(['天氣', '食物', '旅遊', '娛樂', '體育', '本地時事', '購物', '學習', '工作', '健康同健身',
       '宠物', '科技同新闻', '电影同电视剧', '音乐同艺术', '爱好同兴趣', '历史同文学', '社交媒体同网络文化',
       '环境'], dtype=object)

## Checking the Audio and Text label

In [14]:
def playAudio(raw):
    display(Audio(raw))

In [15]:
index = 3

playAudio(df["audio"][index]["bytes"]) 
print(f"Index : {index}")
print(f"Text : {df["sentence"][index]}")
print(f"File: {df["audio"][index]["path"]}")

Index : 3
Text : 周圍都有well-developed霧，嚴重limit我哋嘅visibility，開車嘅時候要小心啲！
File: 1_4.mp3

## Prepare Audio File for Hong Kong Cantonese (Fine tune) Training Dataset

In [16]:
def generateAudioFile(raw : bytes, fileName: str, format_hint="mp3"):
    # Wrap bytes in memory buffer
    audio_buffer = BytesIO(raw)
    # Try to load (pydub guesses format from content or you can force it)
    # audio = AudioSegment.from_file(audio_buffer, format=format_hint)
    data, samplerate = sf.read(audio_buffer)
    # print(samplerate)
    # Write to new file (format guessed from extension)
    sf.write(fileName, data, samplerate)
    
    print(f"Saved via soundfile → {fileName}")

In [17]:
generateAudioFile(df["audio"][index]["bytes"], f"{AudioPATH}/{index}.wav")

Saved via soundfile → ./audio/3.wav

In [18]:
numberSample= 2000 #500
for idx in range(numberSample):
    generateAudioFile(df["audio"][idx]["bytes"], f"{AudioPATH}/{idx}.wav")

Saved via soundfile → ./audio/0.wav
Saved via soundfile → ./audio/1.wav
Saved via soundfile → ./audio/2.wav
Saved via soundfile → ./audio/3.wav
Saved via soundfile → ./audio/4.wav
Saved via soundfile → ./audio/5.wav
Saved via soundfile → ./audio/6.wav
Saved via soundfile → ./audio/7.wav
Saved via soundfile → ./audio/8.wav
Saved via soundfile → ./audio/9.wav
Saved via soundfile → ./audio/10.wav
Saved via soundfile → ./audio/11.wav
Saved via soundfile → ./audio/12.wav
Saved via soundfile → ./audio/13.wav
Saved via soundfile → ./audio/14.wav
Saved via soundfile → ./audio/15.wav
Saved via soundfile → ./audio/16.wav
Saved via soundfile → ./audio/17.wav
Saved via soundfile → ./audio/18.wav
Saved via soundfile → ./audio/19.wav
Saved via soundfile → ./audio/20.wav
Saved via soundfile → ./audio/21.wav
Saved via soundfile → ./audio/22.wav
Saved via soundfile → ./audio/23.wav
Saved via soundfile → ./audio/24.wav
Saved via soundfile → ./audio/25.wav
Saved via soundfile → ./audio/26.wav
Saved via soundfile → ./audio/27.wav
Saved via soundfile → ./audio/28.wav
Saved via soundfile → ./audio/29.wav
Saved via soundfile → ./audio/30.wav
Saved via soundfile → ./audio/31.wav
Saved via soundfile → ./audio/32.wav
Saved via soundfile → ./audio/33.wav
Saved via soundfile → ./audio/34.wav
Saved via soundfile → ./audio/35.wav
Saved via soundfile → ./audio/36.wav
Saved via soundfile → ./audio/37.wav
Saved via soundfile → ./audio/38.wav
Saved via soundfile → ./audio/39.wav
Saved via soundfile → ./audio/40.wav
Saved via soundfile → ./audio/41.wav
Saved via soundfile → ./audio/42.wav
Saved via soundfile → ./audio/43.wav
Saved via soundfile → ./audio/44.wav
Saved via soundfile → ./audio/45.wav
Saved via soundfile → ./audio/46.wav
Saved via soundfile → ./audio/47.wav
Saved via soundfile → ./audio/48.wav
Saved via soundfile → ./audio/49.wav
Saved via soundfile → ./audio/50.wav
Saved via soundfile → ./audio/51.wav
Saved via soundfile → ./audio/52.wav
Saved via soundfile → ./audio/53.wav
Saved via soundfile → ./audio/54.wav
Saved via soundfile → ./audio/55.wav
Saved via soundfile → ./audio/56.wav
Saved via soundfile → ./audio/57.wav
Saved via soundfile → ./audio/58.wav
Saved via soundfile → ./audio/59.wav
Saved via soundfile → ./audio/60.wav
Saved via soundfile → ./audio/61.wav
Saved via soundfile → ./audio/62.wav
Saved via soundfile → ./audio/63.wav
Saved via soundfile → ./audio/64.wav
Saved via soundfile → ./audio/65.wav
Saved via soundfile → ./audio/66.wav
Saved via soundfile → ./audio/67.wav
Saved via soundfile → ./audio/68.wav
Saved via soundfile → ./audio/69.wav
Saved via soundfile → ./audio/70.wav
Saved via soundfile → ./audio/71.wav
Saved via soundfile → ./audio/72.wav
Saved via soundfile → ./audio/73.wav
Saved via soundfile → ./audio/74.wav
Saved via soundfile → ./audio/75.wav
Saved via soundfile → ./audio/76.wav
Saved via soundfile → ./audio/77.wav
Saved via soundfile → ./audio/78.wav
Saved via soundfile → ./audio/79.wav
Saved via soundfile → ./audio/80.wav
Saved via soundfile → ./audio/81.wav
Saved via soundfile → ./audio/82.wav
Saved via soundfile → ./audio/83.wav
Saved via soundfile → ./audio/84.wav
Saved via soundfile → ./audio/85.wav
Saved via soundfile → ./audio/86.wav
Saved via soundfile → ./audio/87.wav
Saved via soundfile → ./audio/88.wav
Saved via soundfile → ./audio/89.wav
Saved via soundfile → ./audio/90.wav
Saved via soundfile → ./audio/91.wav
Saved via soundfile → ./audio/92.wav
Saved via soundfile → ./audio/93.wav
Saved via soundfile → ./audio/94.wav
Saved via soundfile → ./audio/95.wav
Saved via soundfile → ./audio/96.wav
Saved via soundfile → ./audio/97.wav
Saved via soundfile → ./audio/98.wav
Saved via soundfile → ./audio/99.wav
Saved via soundfile → ./audio/100.wav
Saved via soundfile → ./audio/101.wav
Saved via soundfile → ./audio/102.wav
Saved via soundfile → ./audio/103.wav
Saved via soundfile → ./audio/104.wav
Saved via soundfile → ./audio/105.wav
Saved via soundfile → ./audio/106.wav
Saved via soundfile → ./audio/107.wav
Saved via soundfile → ./audio/108.wav
Saved via soundfile → ./audio/109.wav
Saved via soundfile → ./audio/110.wav
Saved via soundfile → ./audio/111.wav
Saved via soundfile → ./audio/112.wav
Saved via soundfile → ./audio/113.wav
Saved via soundfile → ./audio/114.wav
Saved via soundfile → ./audio/115.wav
Saved via soundfile → ./audio/116.wav
Saved via soundfile → ./audio/117.wav
Saved via soundfile → ./audio/118.wav
Saved via soundfile → ./audio/119.wav
Saved via soundfile → ./audio/120.wav
Saved via soundfile → ./audio/121.wav
Saved via soundfile → ./audio/122.wav
Saved via soundfile → ./audio/123.wav
Saved via soundfile → ./audio/124.wav
Saved via soundfile → ./audio/125.wav
Saved via soundfile → ./audio/126.wav
Saved via soundfile → ./audio/127.wav
Saved via soundfile → ./audio/128.wav
Saved via soundfile → ./audio/129.wav
Saved via soundfile → ./audio/130.wav
Saved via soundfile → ./audio/131.wav
Saved via soundfile → ./audio/132.wav
Saved via soundfile → ./audio/133.wav
Saved via soundfile → ./audio/134.wav
Saved via soundfile → ./audio/135.wav
Saved via soundfile → ./audio/136.wav
Saved via soundfile → ./audio/137.wav
Saved via soundfile → ./audio/138.wav
Saved via soundfile → ./audio/139.wav
Saved via soundfile → ./audio/140.wav
Saved via soundfile → ./audio/141.wav
Saved via soundfile → ./audio/142.wav
Saved via soundfile → ./audio/143.wav
Saved via soundfile → ./audio/144.wav
Saved via soundfile → ./audio/145.wav
Saved via soundfile → ./audio/146.wav
Saved via soundfile → ./audio/147.wav
Saved via soundfile → ./audio/148.wav
Saved via soundfile → ./audio/149.wav
Saved via soundfile → ./audio/150.wav
Saved via soundfile → ./audio/151.wav
Saved via soundfile → ./audio/152.wav
Saved via soundfile → ./audio/153.wav
Saved via soundfile → ./audio/154.wav
Saved via soundfile → ./audio/155.wav
Saved via soundfile → ./audio/156.wav
Saved via soundfile → ./audio/157.wav
Saved via soundfile → ./audio/158.wav
Saved via soundfile → ./audio/159.wav
Saved via soundfile → ./audio/160.wav
Saved via soundfile → ./audio/161.wav
Saved via soundfile → ./audio/162.wav
Saved via soundfile → ./audio/163.wav
Saved via soundfile → ./audio/164.wav
Saved via soundfile → ./audio/165.wav
Saved via soundfile → ./audio/166.wav
Saved via soundfile → ./audio/167.wav
Saved via soundfile → ./audio/168.wav
Saved via soundfile → ./audio/169.wav
Saved via soundfile → ./audio/170.wav
Saved via soundfile → ./audio/171.wav
Saved via soundfile → ./audio/172.wav
Saved via soundfile → ./audio/173.wav
Saved via soundfile → ./audio/174.wav
Saved via soundfile → ./audio/175.wav
Saved via soundfile → ./audio/176.wav
Saved via soundfile → ./audio/177.wav
Saved via soundfile → ./audio/178.wav
Saved via soundfile → ./audio/179.wav
Saved via soundfile → ./audio/180.wav
Saved via soundfile → ./audio/181.wav
Saved via soundfile → ./audio/182.wav
Saved via soundfile → ./audio/183.wav
Saved via soundfile → ./audio/184.wav
Saved via soundfile → ./audio/185.wav
Saved via soundfile → ./audio/186.wav
Saved via soundfile → ./audio/187.wav
Saved via soundfile → ./audio/188.wav
Saved via soundfile → ./audio/189.wav
Saved via soundfile → ./audio/190.wav
Saved via soundfile → ./audio/191.wav
Saved via soundfile → ./audio/192.wav
Saved via soundfile → ./audio/193.wav
Saved via soundfile → ./audio/194.wav
Saved via soundfile → ./audio/195.wav
Saved via soundfile → ./audio/196.wav
Saved via soundfile → ./audio/197.wav
Saved via soundfile → ./audio/198.wav
Saved via soundfile → ./audio/199.wav
Saved via soundfile → ./audio/200.wav
Saved via soundfile → ./audio/201.wav
Saved via soundfile → ./audio/202.wav
Saved via soundfile → ./audio/203.wav
Saved via soundfile → ./audio/204.wav
Saved via soundfile → ./audio/205.wav
Saved via soundfile → ./audio/206.wav
Saved via soundfile → ./audio/207.wav
Saved via soundfile → ./audio/208.wav
Saved via soundfile → ./audio/209.wav
Saved via soundfile → ./audio/210.wav
Saved via soundfile → ./audio/211.wav
Saved via soundfile → ./audio/212.wav
Saved via soundfile → ./audio/213.wav
Saved via soundfile → ./audio/214.wav
Saved via soundfile → ./audio/215.wav
Saved via soundfile → ./audio/216.wav
Saved via soundfile → ./audio/217.wav
Saved via soundfile → ./audio/218.wav
Saved via soundfile → ./audio/219.wav
Saved via soundfile → ./audio/220.wav
Saved via soundfile → ./audio/221.wav
Saved via soundfile → ./audio/222.wav
Saved via soundfile → ./audio/223.wav
Saved via soundfile → ./audio/224.wav
Saved via soundfile → ./audio/225.wav
Saved via soundfile → ./audio/226.wav
Saved via soundfile → ./audio/227.wav
Saved via soundfile → ./audio/228.wav
Saved via soundfile → ./audio/229.wav
Saved via soundfile → ./audio/230.wav
Saved via soundfile → ./audio/231.wav
Saved via soundfile → ./audio/232.wav
Saved via soundfile → ./audio/233.wav
Saved via soundfile → ./audio/234.wav
Saved via soundfile → ./audio/235.wav
Saved via soundfile → ./audio/236.wav
Saved via soundfile → ./audio/237.wav
Saved via soundfile → ./audio/238.wav
Saved via soundfile → ./audio/239.wav
Saved via soundfile → ./audio/240.wav
Saved via soundfile → ./audio/241.wav
Saved via soundfile → ./audio/242.wav
Saved via soundfile → ./audio/243.wav
Saved via soundfile → ./audio/244.wav
Saved via soundfile → ./audio/245.wav
Saved via soundfile → ./audio/246.wav
Saved via soundfile → ./audio/247.wav
Saved via soundfile → ./audio/248.wav
Saved via soundfile → ./audio/249.wav
Saved via soundfile → ./audio/250.wav
Saved via soundfile → ./audio/251.wav
Saved via soundfile → ./audio/252.wav
Saved via soundfile → ./audio/253.wav
Saved via soundfile → ./audio/254.wav
Saved via soundfile → ./audio/255.wav
Saved via soundfile → ./audio/256.wav
Saved via soundfile → ./audio/257.wav
Saved via soundfile → ./audio/258.wav
Saved via soundfile → ./audio/259.wav
Saved via soundfile → ./audio/260.wav
Saved via soundfile → ./audio/261.wav
Saved via soundfile → ./audio/262.wav
Saved via soundfile → ./audio/263.wav
Saved via soundfile → ./audio/264.wav
Saved via soundfile → ./audio/265.wav
Saved via soundfile → ./audio/266.wav
Saved via soundfile → ./audio/267.wav
Saved via soundfile → ./audio/268.wav
Saved via soundfile → ./audio/269.wav
Saved via soundfile → ./audio/270.wav
Saved via soundfile → ./audio/271.wav
Saved via soundfile → ./audio/272.wav
Saved via soundfile → ./audio/273.wav
Saved via soundfile → ./audio/274.wav
Saved via soundfile → ./audio/275.wav
Saved via soundfile → ./audio/276.wav
Saved via soundfile → ./audio/277.wav
Saved via soundfile → ./audio/278.wav
Saved via soundfile → ./audio/279.wav
Saved via soundfile → ./audio/280.wav
Saved via soundfile → ./audio/281.wav
Saved via soundfile → ./audio/282.wav
Saved via soundfile → ./audio/283.wav
Saved via soundfile → ./audio/284.wav
Saved via soundfile → ./audio/285.wav
Saved via soundfile → ./audio/286.wav
Saved via soundfile → ./audio/287.wav
Saved via soundfile → ./audio/288.wav
Saved via soundfile → ./audio/289.wav
Saved via soundfile → ./audio/290.wav
Saved via soundfile → ./audio/291.wav
Saved via soundfile → ./audio/292.wav
Saved via soundfile → ./audio/293.wav
Saved via soundfile → ./audio/294.wav
Saved via soundfile → ./audio/295.wav
Saved via soundfile → ./audio/296.wav
Saved via soundfile → ./audio/297.wav
Saved via soundfile → ./audio/298.wav
Saved via soundfile → ./audio/299.wav
Saved via soundfile → ./audio/300.wav
Saved via soundfile → ./audio/301.wav
Saved via soundfile → ./audio/302.wav
Saved via soundfile → ./audio/303.wav
Saved via soundfile → ./audio/304.wav
Saved via soundfile → ./audio/305.wav
Saved via soundfile → ./audio/306.wav
Saved via soundfile → ./audio/307.wav
Saved via soundfile → ./audio/308.wav
Saved via soundfile → ./audio/309.wav
Saved via soundfile → ./audio/310.wav
Saved via soundfile → ./audio/311.wav
Saved via soundfile → ./audio/312.wav
Saved via soundfile → ./audio/313.wav
Saved via soundfile → ./audio/314.wav
Saved via soundfile → ./audio/315.wav
Saved via soundfile → ./audio/316.wav
Saved via soundfile → ./audio/317.wav
Saved via soundfile → ./audio/318.wav
Saved via soundfile → ./audio/319.wav
Saved via soundfile → ./audio/320.wav
Saved via soundfile → ./audio/321.wav
Saved via soundfile → ./audio/322.wav
Saved via soundfile → ./audio/323.wav
Saved via soundfile → ./audio/324.wav
Saved via soundfile → ./audio/325.wav
Saved via soundfile → ./audio/326.wav
Saved via soundfile → ./audio/327.wav
Saved via soundfile → ./audio/328.wav
Saved via soundfile → ./audio/329.wav
Saved via soundfile → ./audio/330.wav
Saved via soundfile → ./audio/331.wav
Saved via soundfile → ./audio/332.wav
Saved via soundfile → ./audio/333.wav
Saved via soundfile → ./audio/334.wav
Saved via soundfile → ./audio/335.wav
Saved via soundfile → ./audio/336.wav
Saved via soundfile → ./audio/337.wav
Saved via soundfile → ./audio/338.wav
Saved via soundfile → ./audio/339.wav
Saved via soundfile → ./audio/340.wav
Saved via soundfile → ./audio/341.wav
Saved via soundfile → ./audio/342.wav
Saved via soundfile → ./audio/343.wav
Saved via soundfile → ./audio/344.wav
Saved via soundfile → ./audio/345.wav
Saved via soundfile → ./audio/346.wav
Saved via soundfile → ./audio/347.wav
Saved via soundfile → ./audio/348.wav
Saved via soundfile → ./audio/349.wav
Saved via soundfile → ./audio/350.wav
Saved via soundfile → ./audio/351.wav
Saved via soundfile → ./audio/352.wav
Saved via soundfile → ./audio/353.wav
Saved via soundfile → ./audio/354.wav
Saved via soundfile → ./audio/355.wav
Saved via soundfile → ./audio/356.wav
Saved via soundfile → ./audio/357.wav
Saved via soundfile → ./audio/358.wav
Saved via soundfile → ./audio/359.wav
Saved via soundfile → ./audio/360.wav
Saved via soundfile → ./audio/361.wav
Saved via soundfile → ./audio/362.wav
Saved via soundfile → ./audio/363.wav
Saved via soundfile → ./audio/364.wav
Saved via soundfile → ./audio/365.wav
Saved via soundfile → ./audio/366.wav
Saved via soundfile → ./audio/367.wav
Saved via soundfile → ./audio/368.wav
Saved via soundfile → ./audio/369.wav
Saved via soundfile → ./audio/370.wav
Saved via soundfile → ./audio/371.wav
Saved via soundfile → ./audio/372.wav
Saved via soundfile → ./audio/373.wav
Saved via soundfile → ./audio/374.wav
Saved via soundfile → ./audio/375.wav
Saved via soundfile → ./audio/376.wav
Saved via soundfile → ./audio/377.wav
Saved via soundfile → ./audio/378.wav
Saved via soundfile → ./audio/379.wav
Saved via soundfile → ./audio/380.wav
Saved via soundfile → ./audio/381.wav
Saved via soundfile → ./audio/382.wav
Saved via soundfile → ./audio/383.wav
Saved via soundfile → ./audio/384.wav
Saved via soundfile → ./audio/385.wav
Saved via soundfile → ./audio/386.wav
Saved via soundfile → ./audio/387.wav
Saved via soundfile → ./audio/388.wav
Saved via soundfile → ./audio/389.wav
Saved via soundfile → ./audio/390.wav
Saved via soundfile → ./audio/391.wav
Saved via soundfile → ./audio/392.wav
Saved via soundfile → ./audio/393.wav
Saved via soundfile → ./audio/394.wav
Saved via soundfile → ./audio/395.wav
Saved via soundfile → ./audio/396.wav
Saved via soundfile → ./audio/397.wav
Saved via soundfile → ./audio/398.wav
Saved via soundfile → ./audio/399.wav
Saved via soundfile → ./audio/400.wav
Saved via soundfile → ./audio/401.wav
Saved via soundfile → ./audio/402.wav
Saved via soundfile → ./audio/403.wav
Saved via soundfile → ./audio/404.wav
Saved via soundfile → ./audio/405.wav
Saved via soundfile → ./audio/406.wav
Saved via soundfile → ./audio/407.wav
Saved via soundfile → ./audio/408.wav
Saved via soundfile → ./audio/409.wav
Saved via soundfile → ./audio/410.wav
Saved via soundfile → ./audio/411.wav
Saved via soundfile → ./audio/412.wav
Saved via soundfile → ./audio/413.wav
Saved via soundfile → ./audio/414.wav
Saved via soundfile → ./audio/415.wav
Saved via soundfile → ./audio/416.wav
Saved via soundfile → ./audio/417.wav
Saved via soundfile → ./audio/418.wav
Saved via soundfile → ./audio/419.wav
Saved via soundfile → ./audio/420.wav
Saved via soundfile → ./audio/421.wav
Saved via soundfile → ./audio/422.wav
Saved via soundfile → ./audio/423.wav
Saved via soundfile → ./audio/424.wav
Saved via soundfile → ./audio/425.wav
Saved via soundfile → ./audio/426.wav
Saved via soundfile → ./audio/427.wav
Saved via soundfile → ./audio/428.wav
Saved via soundfile → ./audio/429.wav
Saved via soundfile → ./audio/430.wav
Saved via soundfile → ./audio/431.wav
Saved via soundfile → ./audio/432.wav
Saved via soundfile → ./audio/433.wav
Saved via soundfile → ./audio/434.wav
Saved via soundfile → ./audio/435.wav
Saved via soundfile → ./audio/436.wav
Saved via soundfile → ./audio/437.wav
Saved via soundfile → ./audio/438.wav
Saved via soundfile → ./audio/439.wav
Saved via soundfile → ./audio/440.wav
Saved via soundfile → ./audio/441.wav
Saved via soundfile → ./audio/442.wav
Saved via soundfile → ./audio/443.wav
Saved via soundfile → ./audio/444.wav
Saved via soundfile → ./audio/445.wav
Saved via soundfile → ./audio/446.wav
Saved via soundfile → ./audio/447.wav
Saved via soundfile → ./audio/448.wav
Saved via soundfile → ./audio/449.wav
Saved via soundfile → ./audio/450.wav
Saved via soundfile → ./audio/451.wav
Saved via soundfile → ./audio/452.wav
Saved via soundfile → ./audio/453.wav
Saved via soundfile → ./audio/454.wav
Saved via soundfile → ./audio/455.wav
Saved via soundfile → ./audio/456.wav
Saved via soundfile → ./audio/457.wav
Saved via soundfile → ./audio/458.wav
Saved via soundfile → ./audio/459.wav
Saved via soundfile → ./audio/460.wav
Saved via soundfile → ./audio/461.wav
Saved via soundfile → ./audio/462.wav
Saved via soundfile → ./audio/463.wav
Saved via soundfile → ./audio/464.wav
Saved via soundfile → ./audio/465.wav
Saved via soundfile → ./audio/466.wav
Saved via soundfile → ./audio/467.wav
Saved via soundfile → ./audio/468.wav
Saved via soundfile → ./audio/469.wav
Saved via soundfile → ./audio/470.wav
Saved via soundfile → ./audio/471.wav
Saved via soundfile → ./audio/472.wav
Saved via soundfile → ./audio/473.wav
Saved via soundfile → ./audio/474.wav
Saved via soundfile → ./audio/475.wav
Saved via soundfile → ./audio/476.wav
Saved via soundfile → ./audio/477.wav
Saved via soundfile → ./audio/478.wav
Saved via soundfile → ./audio/479.wav
Saved via soundfile → ./audio/480.wav
Saved via soundfile → ./audio/481.wav
Saved via soundfile → ./audio/482.wav
Saved via soundfile → ./audio/483.wav
Saved via soundfile → ./audio/484.wav
Saved via soundfile → ./audio/485.wav
Saved via soundfile → ./audio/486.wav
Saved via soundfile → ./audio/487.wav
Saved via soundfile → ./audio/488.wav
Saved via soundfile → ./audio/489.wav
Saved via soundfile → ./audio/490.wav
Saved via soundfile → ./audio/491.wav
Saved via soundfile → ./audio/492.wav
Saved via soundfile → ./audio/493.wav
Saved via soundfile → ./audio/494.wav
Saved via soundfile → ./audio/495.wav
Saved via soundfile → ./audio/496.wav
Saved via soundfile → ./audio/497.wav
Saved via soundfile → ./audio/498.wav
Saved via soundfile → ./audio/499.wav
Saved via soundfile → ./audio/500.wav
Saved via soundfile → ./audio/501.wav
Saved via soundfile → ./audio/502.wav
Saved via soundfile → ./audio/503.wav
Saved via soundfile → ./audio/504.wav
Saved via soundfile → ./audio/505.wav
Saved via soundfile → ./audio/506.wav
Saved via soundfile → ./audio/507.wav
Saved via soundfile → ./audio/508.wav
Saved via soundfile → ./audio/509.wav
Saved via soundfile → ./audio/510.wav
Saved via soundfile → ./audio/511.wav
Saved via soundfile → ./audio/512.wav
Saved via soundfile → ./audio/513.wav
Saved via soundfile → ./audio/514.wav
Saved via soundfile → ./audio/515.wav
Saved via soundfile → ./audio/516.wav
Saved via soundfile → ./audio/517.wav
Saved via soundfile → ./audio/518.wav
Saved via soundfile → ./audio/519.wav
Saved via soundfile → ./audio/520.wav
Saved via soundfile → ./audio/521.wav
Saved via soundfile → ./audio/522.wav
Saved via soundfile → ./audio/523.wav
Saved via soundfile → ./audio/524.wav
Saved via soundfile → ./audio/525.wav
Saved via soundfile → ./audio/526.wav
Saved via soundfile → ./audio/527.wav
Saved via soundfile → ./audio/528.wav

In [19]:
import random

# Generate a random integer between 1 and 10 (inclusive)
random_integer = random.randint(1, numberSample)
print(random_integer)

1517

In [20]:
# generateAudioFile(df["audio"][random_integer]["bytes"], f"{AudioPATH}/ref_voice/alienkevin.wav")

### Resample ALL Audio file Qwen3 ASR requirement only support 24Khz

In [21]:
import librosa
import soundfile as sf

# # wav, sr = librosa.load(f"{AudioPATH}/2.wav", sr=None)
# # wav, sr = librosa.load(RefVoicePATHWav, sr=None)
# wav , sr = librosa.load(f"{AudioPATH}/ref_voice/alienkevin.wav", sr=None)
# print(f"Original Sample rate: {sr}")

# if sr != 24000:
#     newWav = librosa.resample(wav, orig_sr=sr, target_sr=24000)
#     # Add normalization to prevent clipping
#     newWav = librosa.util.normalize(newWav)
#     sf.write(f"{AudioPATH}/ref_voice/alienkevin.wav", newWav, 24000)
#     # print(f"New Sample rate: {tempSR}")
#     sr = 24000
# else:
#      # Normalize even if the sample rate is correct
#     newWav = librosa.util.normalize(wav)
#     sf.write(audioPath, newWav, targetSR)
#     print(f"Audio File ready support target sample rate: {targetSR}")

In [22]:
wav, sr = librosa.load(f"{AudioPATH}/1.wav", sr=None)
sr

/home/aifather/venv-qwen3asr/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

16000

In [23]:
def batchResample(audioPath, targetSR=24000):
    wav, sr = librosa.load(audioPath, sr=None)
    if sr != 24000:
        newWav = librosa.resample(wav, orig_sr=sr, target_sr=24000)
        # Add normalization to prevent clipping
        newWav = librosa.util.normalize(newWav)
        sf.write(audioPath, newWav, targetSR)
        print(f"Saved resample soundfile → {audioPath}")
    else:
        # Normalize even if the sample rate is correct
        newWav = librosa.util.normalize(wav)
        sf.write(audioPath, newWav, targetSR)
        print(f"Audio File ready support target sample rate: {targetSR}")

In [24]:
# numberSample= 500
# for idx in range(numberSample):
#     batchResample(f"{AudioPATH}/{idx}.wav", targetSR=24000)

In [25]:
# extract Dataframe

In [26]:
selectedDF =df[:numberSample].copy()

In [27]:
selectedDF

,audio,sentence,topic
0,{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x...,你知唔知今日嘅temperature會落到低至10度，一定要著厚d嘅clothes啊！,天氣
1,{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x...,我check咗天氣app，佢話今日會有thunderstorm，最好唔好去戶外行嘅。,天氣
2,{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x...,飛機已經被grounded喇，因為typhoon signal已經升到No.8嚟啦。,天氣
3,{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x...,周圍都有well-developed霧，嚴重limit我哋嘅visibility，開車嘅時候...,天氣
4,{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x...,Forecast話晚上嘅weather會變得好cold，會降到freezing point，...,天氣
...,...,...,...
1995,{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x...,你嘅work attitude十分影响你嘅career development，要常常che...,工作
1996,{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x...,有時候，唔係要work harder，而係要work smarter。,工作
1997,{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x...,Job satisfaction同money唔一定要相反，有時你最享受嘅work可能就係你最赚嘅。,工作
1998,{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x...,睇得太远可能會miss住身邊嘅opportunity，即使個目标未到，都要appreciat...,工作
1999,{'bytes': b'ID3\x04\x00\x00\x00\x00\x00#TSSE\x...,Communication skills係workplace上最重要嘅一種skills，有好...,工作

### Generate JSONL file for prepare Training data

In [28]:
def generateJSONFile(dataFrame, audioDirectory, outputFile="train.jsonl"):
    with open(outputFile, "w", encoding="utf-8") as f:
        for i, row in dataFrame.iterrows():
            obj = {
                "audio": f"{audioDirectory}/{i}.wav",
                "text": f"language Cantonese<asr_text>{row['sentence']}",   # map sentence -> text
            }
            # ensure_ascii=False keeps Chinese characters, etc.
            f.write(json.dumps(obj, ensure_ascii=False) + "\n")

In [29]:
generateJSONFile(selectedDF, AudioPATH, outputFile="train_raw.jsonl")

In [56]:
def split_jsonl_dataset(
    input_file: str = "train_raw.jsonl",
    val_size: float = 0.2,
    random_state: int = 42,
    output_dir: str = ".",
    train_output_name: str = "train.jsonl",
    val_output_name: str = "val.jsonl"
) -> tuple[list[dict], list[dict]]:
    """
    Splits a JSONL dataset file into training and validation sets.
    
    Args:
        input_file (str): Path to your raw JSONL file (default: train_raw.jsonl).
        val_size (float): Percentage of the data to use for the validation/test set 
                          (e.g. 0.2 = 20%). Must be between 0 and 1.
        random_state (int): Random seed for reproducible splits (default: 42).
        output_dir (str): Directory where train.jsonl and val.jsonl will be saved.
        train_output_name (str): Filename for the training set.
        val_output_name (str): Filename for the validation set.
    
    Returns:
        tuple: (train_data, val_data) — lists of dictionaries for further use if needed.
    
    Example usage:
        train_data, val_data = split_jsonl_dataset(val_size=0.15)
        # or
        split_jsonl_dataset("train_raw.jsonl", val_size=0.2, output_dir="./data_split")
    """
    # 1. Load the entire JSONL file
    with open(input_file, "r", encoding="utf-8") as f:
        data = [json.loads(line) for line in f]

    print(f"Loaded {len(data)} samples from {input_file}")

    # 2. Split into train + validation (sklearn handles shuffling automatically)
    train_data, val_data = train_test_split(
        data,
        test_size=val_size,
        random_state=random_state
    )

    # 3. Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)

    # 4. Save training set
    train_path = os.path.join(output_dir, train_output_name)
    with open(train_path, "w", encoding="utf-8") as f:
        for item in train_data:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

    # 5. Save validation set
    val_path = os.path.join(output_dir, val_output_name)
    with open(val_path, "w", encoding="utf-8") as f:
        for item in val_data:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

    print(f"✅ Split complete!")
    print(f"   • Training samples : {len(train_data):,}")
    print(f"   • Validation samples: {len(val_data):,}")
    print(f"   • Files saved → {train_path}")
    print(f"   • Files saved → {val_path}")

    return train_data, val_data

In [57]:
# Just run this in your script/notebook
split_jsonl_dataset(val_size=0.3)                    # 20% validation
# or
# split_jsonl_dataset(val_size=0.15, output_dir="./my_split")  # 15% validation

Loaded 2000 samples from train_raw.jsonl
✅ Split complete!
   • Training samples : 1,400
   • Validation samples: 600
   • Files saved → ./train.jsonl
   • Files saved → ./val.jsonl

([{'audio': './audio/836.wav',
   'text': 'language Cantonese<asr_text>前晚我試咗嚟自Thailand嘅tom yum soup，味道真係足夠spicy同refreshing，正宗嘅泰國菜味道！'},
  {'audio': './audio/575.wav',
   'text': 'language Cantonese<asr_text>我琴日去左個gallery，有好多modern art展品，雖然有啲我都唔知佢想表達咩，但係我都鐘意去思考同欣賞佢哋！'},
  {'audio': './audio/557.wav',
   'text': 'language Cantonese<asr_text>昨晚上我落廚，整咗煎鴨胸，搭配fresh嘅蔬菜同薯蓉，持平講，冇得嘢比自家煮嘅飯更好味！'},
  {'audio': './audio/1235.wav',
   'text': 'language Cantonese<asr_text>進行terminal射擊運動幫助我哋improve concentration，亦都需要穩定嘅hand control。'},
  {'audio': './audio/1360.wav',
   'text': 'language Cantonese<asr_text>Teamwork係件好事，大家都需要cooperate，咁先能達到the best results。'},
  {'audio': './audio/1347.wav',
   'text': 'language Cantonese<asr_text>我喺Apple store買咗新款iPhone，感覺好好，用得都好開心咁！'},
  {'audio': './audio/1161.wav',
   'text': 'language Cantonese<asr_text>Sogo嘅cosmetic section真係好吸引，各種品牌都有，仲可以試用下先決定買邊款。'},
  {'audio': './audio/1442.wav',
   'text': 'language Cantonese<asr_text>無論考試嘅result如何，最重要嘅係你吸收咗幾多knowledge。'},
  {'audio': './audio/286.wav',
   'text': 'language Cantonese<asr_text>我揾到一个好的deal去Japan ski，冬天来个snow adventure真係好刺激呀！'},
  {'audio': './audio/1604.wav',
   'text': 'language Cantonese<asr_text>Affordable housing係香港嘅長遠目標，但我哋都要正視其中存在嘅financial challenges，理性討論可行嘅solution。'},
  {'audio': './audio/1057.wav',
   'text': 'language Cantonese<asr_text>玩網球唔只係trained up我哋嘅hand-eye coordination，佢更係一個great嘅方式去release我哋嘅energy。'},
  {'audio': './audio/598.wav',
   'text': 'language Cantonese<asr_text>本地嘅空氣污染問題非常嚴重，呼籲喺市區設置更多air quality monitoring stations。'},
  {'audio': './audio/932.wav',
   'text': 'language Cantonese<asr_text>晚餐去咗一間西餐廳，嗰度嘅steak煎得just right，好juicy，完全match我嘅口味！" '},
  {'audio': './audio/1461.wav',
   'text': 'language Cantonese<asr_text>早上畀雷电惊醒，睇吓窗外雨落落，大gao都wet晒。'},
  {'audio': './audio/1637.wav',
   'text': 'language Cantonese<asr_text>Demonstrate你嘅leadership skills 可以帮助你get promoted.'},
  {'audio': './audio/1587.wav',
   'text': 'language Cantonese<asr_text>我喺假日嘅時候，都會享受下去beach party，感受下sunshine同海風嘅調調.'},
  {'audio': './audio/1040.wav',
   'text': 'language Cantonese<asr_text>喺Korea嘅Seoul，踏過秋天嘅Maple leaves，係一份romantic嘅experience！'},
  {'audio': './audio/1230.wav',
   'text': 'language Cantonese<asr_text>打乒乓球可以促進我哋嘅hand-eye coordination，仲可以enhance我哋嘅strategic thinking。'},
  {'audio': './audio/806.wav',
   'text': 'language Cantonese<asr_text>我哋學嘅嘢唔一定要用黎應考，學習就係去explore世界，開拓我哋嘅眼界'},
  {'audio': './audio/904.wav',
   'text': 'language Cantonese<asr_text>學習嘅journey唔係straight forward，會有ups同降，但其中嘅hardship會make我哋stronger。'},
  {'audio': './audio/1679.wav',
   'text': 'language Cantonese<asr_text>我會喺電腦度download啲interesting app，玩下圖像編輯或者做下GIF，感覺自己好creative.'},
  {'audio': './audio/1204.wav',
   'text': 'language Cantonese<asr_text>大热天嗮舖冰凉cold brew coffee，refreshing到令人feel like flying！'},
  {'audio': './audio/767.wav',
   'text': 'language Cantonese<asr_text>我雖然唔識畫畫，但係去過‘Art Basel’嘅artist展覽後都係感到好inspired，especially嗰d abstract art piece！'},
  {'audio': './audio/609.wav',
   'text': 'language Cantonese<asr_text>假期期間嘅sale真係not to be missed,通常都會買到好多平價嘅優質goods。'},
  {'audio': './audio/1992.wav',
   'text': 'language Cantonese<asr_text>做自己嘅learning plan，了解自己嘅學習style係好重要嘅一步。'},
  {'audio': './audio/1564.wav',
   'text': 'language Cantonese<asr_text>你可能试过很多ravioli，但这个虾饺ravioli，外面smooth and delicate，内里full of juicy shrimp，真的让人有再吃一笼的urge!'},
  {'audio': './audio/1422.wav',
   'text': 'language Cantonese<asr_text>香港downtown空氣污染程度己取得some progress但我哋仍需努力改善air quality，要爭取sustainable future。'},
  {'audio': './audio/1010.wav',
   'text': 'language Cantonese<asr_text>你要work independently但同時都要value team collaboration，呢樣先係平衡。'},
  {'audio': './audio/493.wav',
   'text': 'language Cantonese<asr_text>學游泳唔止可以enhance muscular strength，亦都可以學到rescue skills，真係一項好有價值嘅sport。'},
  {'audio': './audio/1320.wav',
   'text': 'language Cantonese<asr_text>慢跑係一種很好嘅 low-impact exercise，適合所有年齡層嘅人。'},
  {'audio': './audio/277.wav',
   'text': 'language Cantonese<asr_text>我剛剛嘗試了個新開嘅Vietnamese restaurant，嗰個Pho味道rich同濃郁，真係很impressive！'},
  {'audio': './audio/1846.wav',
   'text': 'language Cantonese<asr_text>你去過Thailand嘅Bangkok未， hawker food嘅獨特味道一定會讓你心滿意足。" '},
  {'audio': './audio/358.wav',
   'text': 'language Cantonese<asr_text>Dinner後可以去海边，預計會有一個perfect sunset呢。'},
  {'audio': './audio/1110.wav',
   'text': 'language Cantonese<asr_text>上班路上嘅wind真的吹得太顶，连行都成问題。'},
  {'audio': './audio/236.wav',
   'text': 'language Cantonese<asr_text>我最like嘅一個活動就係每年black Friday sales，可以用最抵價錢買到最高質素嘅goods，真係超爽！'},
  {'audio': './audio/551.wav',
   'text': 'language Cantonese<asr_text>初春一下sunshine一下喺冷冻，天气变幻莫测。'},
  {'audio': './audio/1867.wav',
   'text': 'language Cantonese<asr_text>做gymnastics可以增强你嘅flexibility同balance，更可以improve你嘅body control能力呢。'},
  {'audio': './audio/1812.wav',
   'text': 'language Cantonese<asr_text>Teamwork係成功嘅key，大家要齐心协力。'},
  {'audio': './audio/208.wav',
   'text': 'language Cantonese<asr_text>我最喜歡就係去book store買咗本新出版嘅novel，每次睇書都可以放鬆自己，好enjoy呢種feel。'},
  {'audio': './audio/1386.wav',
   'text': 'language Cantonese<asr_text>想饮杯街边freshly squeezed果汁，手工作，natural goodness，keep you energised整天！'},
  {'audio': './audio/1560.wav',
   'text': 'language Cantonese<asr_text>星期六forecast话有high chance of thunderstorm，可能要留喺屋企啦。'},
  {'audio': './audio/58.wav',
   'text': 'language Cantonese<asr_text>我喺holiday鐘意去outlet購物，可以買到打折嘅branded goods，價格吓人，甚至可以買到half price，又可以save money。'},
  {'audio': './audio/631.wav',
   'text': 'language Cantonese<asr_text>碌嘅時候，唔好forget去appreciate你工作嘅value。'},
  {'audio': './audio/1961.wav',
   'text': 'language Cantonese<asr_text>我會選擇go jogging，因為呢個運動可以improve我嘅lung function同令我嘅心臟變得更healthy。'},
  {'audio': './audio/1859.wav',
   'text': 'language Cantonese<asr_text>我好鍾意唱karaoke，可以唱出我嘅emotion，好享受嘅一個娛樂活動。'},
  {'audio': './audio/1816.wav',
   'text': 'language Cantonese<asr_text>Stay organized唔只令你嘅workspace整齐，同时令你work efficiently。'},
  {'audio': './audio/363.wav',
   'text': 'language Cantonese<asr_text>如果你计划出去hiking，记得check下weather forecast，话畀你听可能会有thunderstorms。'},
  {'audio': './audio/505.wav',
   'text': 'language Cantonese<asr_text>本地周末遊樂設施不足，有需要建設更多community recreational facilities。'},
  {'audio': './audio/1165.wav',
   'text': 'language Cantonese<asr_text>Harbour City嘅Designer Handbag真係要抵制唔住嘅誘惑，即使價錢好貴都值得！'},
  {'audio': './audio/1121.wav',
   'text': 'language Cantonese<asr_text>有時我哋睇电视嘅時候，就会eat popcorn，crunchy texture令人stop不了手！'},
  {'audio': './audio/1629.wav',
   'text': 'language Cantonese<asr_text>學習唔係越多越好，重要係你digest到你所學嘅知識。'},
  {'audio': './audio/1216.wav',
   'text': 'language Cantonese<asr_text>喺Greece嘅Athens，遊覽過嘅Acropolis，係一種incredible嘅ancient wonder！'},
  {'audio': './audio/1151.wav',
   'text': 'language Cantonese<asr_text>香港嘅Education system越嚟越壓力大，我哋需要讓學生enjoy their childhood。'},
  {'audio': './audio/1124.wav',
   'text': 'language Cantonese<asr_text>喺Iceland嘅Reykjavik, 睇日出嘅Midnight Sun，真係breathtaking嘅scene!'},
  {'audio': './audio/1594.wav',
   'text': 'language Cantonese<asr_text>跳舞唔只能show your creativity，亦都係一種fun way做運動，能提升你嘅flexibility和coordination。'},
  {'audio': './audio/118.wav',
   'text': 'language Cantonese<asr_text>我好鍾意去karaoke同朋友唱歌，每次去都唔覺得boring，我同我朋友們都有好多fun。'},
  {'audio': './audio/1249.wav',
   'text': 'language Cantonese<asr_text>我同朋友去咗Tiffany嗰間鑽石專賣店，睇到好靚嘅necklace，好想買黎送比女朋友呀！'},
  {'audio': './audio/1993.wav',
   'text': 'language Cantonese<asr_text>唔怕改變，keep an open mind，接受新知識和新嘅learning methods。'},
  {'audio': './audio/522.wav',
   'text': 'language Cantonese<asr_text>Remember，學習唔只係about score，理解同meow material嘅process都好重要。'},
  {'audio': './audio/513.wav',
   'text': 'language Cantonese<asr_text>我喺online平台上面買嘅時候，我會check佢哋嘅reviews先，我覺得這是一個smart move。'},
  {'audio': './audio/81.wav',
   'text': 'language Cantonese<asr_text>喺一個新嘅job position，我哋需要有一個open mind，ready咗去學習新嘅skills同face新嘅挑戰。" '},
  {'audio': './audio/915.wav',
   'text': 'language Cantonese<asr_text>如果你能adapt到新嘅工作環境，你就會更quickly進步。'},
  {'audio': './audio/1018.wav',
   'text': 'language Cantonese<asr_text>今晚果个moon真係好bright，稍微点都唔feel寂寞。'},
  {'audio': './audio/380.wav',
   'text': 'language Cantonese<asr_text>下个星期我要去深圳Bay Park玩，欣赏下嘅modern city view。'},
  {'audio': './audio/1029.wav',
   'text': 'language Cantonese<asr_text>午餐時間，我鍾意一個人食嘅就系這個avocado salad，加咗好多fresh veggies，完全health conscious食物嚟喎！'},
  {'audio': './audio/1688.wav',
   'text': 'language Cantonese<asr_text>做Karate可以讓你improve self-discipline同boost你嘅self-confidence。'},
  {'audio': './audio/84.wav',
   'text': 'language Cantonese<asr_text>我好贊同flexible working hours，咁樣可以更好嘅balance我嘅工作同生活。'},
  {'audio': './audio/1677.wav',
   'text': 'language Cantonese<asr_text>我鍾意去concert，feel到啲singer嘅energy，真係好震撼.'},
  {'audio': './audio/329.wav',
   'text': 'language Cantonese<asr_text>我睇到個discount code，可以馬上去網上買啲我之前想買但覺得太貴嘅品牌服裝，真係太lucky啦！'},
  {'audio': './audio/6.wav',
   'text': 'language Cantonese<asr_text>你有冇見過咁震撼嘅sunset? 天氣真係好perfect，可以坐下嚟慢慢欣賞。" '},
  {'audio': './audio/745.wav',
   'text': 'language Cantonese<asr_text>我平時唔係咁鍾意飲coffee，但係如果係星巴克嘅Caramel Macchiato，我就一定會買枝！'},
  {'audio': './audio/1553.wav',
   'text': 'language Cantonese<asr_text>雨勢好big，feel像typhoon来咗，记得关窗啦。'},
  {'audio': './audio/914.wav',
   'text': 'language Cantonese<asr_text>我會focus喺完成我嘅project, 工作仔我要balance嗰啲細節。'},
  {'audio': './audio/873.wav',
   'text': 'language Cantonese<asr_text>Boxing唔只是單純嘅打擊，其實佢涉及到嘅strategy同技巧都非常深奧。'},
  {'audio': './audio/451.wav',
   'text': 'language Cantonese<asr_text>今天可能有會thunderstorm，出门最好配备得完整一啲。'},
  {'audio': './audio/490.wav',
   'text': 'language Cantonese<asr_text>去踩單車唔單止可以scenery俾眼光，而且亦都可以increase stamina.'},
  {'audio': './audio/1480.wav',
   'text': 'language Cantonese<asr_text>喺Australia嘅Great Barrier Reef潛水, 就好似喺amazing嘅underwater world咁！'},
  {'audio': './audio/287.wav',
   'text': 'language Cantonese<asr_text>我plan去France学cooking，學下點煮好味嘅French cuisine好正呀！'},
  {'audio': './audio/948.wav',
   'text': 'language Cantonese<asr_text>喺India嘅Agra，瞓到嗰琴間Taj Mahal，呢個marvelous嘅monument真係leave咗深刻嘅impression!'},
  {'audio': './audio/1985.wav',
   'text': 'language Cantonese<asr_text>學習嘅journey中，唔係只睇成果，過程都好重要。'},
  {'audio': './audio/1368.wav',
   'text': 'language Cantonese<asr_text>Decision-making能力可以幫助你喺multiple options中揀選最appropriate的一个，并且係timely manner下面進行，以確保工作進度唔會被delay。'},
  {'audio': './audio/1146.wav',
   'text': 'language Cantonese<asr_text>玩网球可以幫助我哋boost我地嘅endurance同burn calories.'},
  {'audio': './audio/705.wav',
   'text': 'language Cantonese<asr_text>我成日都話我嘅朋友，唔好忽視咗online shopping，有時候you can find some hidden gems。'},
  {'audio': './audio/1726.wav',
   'text': 'language Cantonese<asr_text>Fake it till you make it, 唔好怕初次做错，学习就系出錯中嚟." '},
  {'audio': './audio/1701.wav',
   'text': 'language Cantonese<asr_text>Traffic congestion喺Peak hour變得普遍，政府需要實行effective measures解決。'},
  {'audio': './audio/1628.wav',
   'text': 'language Cantonese<asr_text>唔同科目可能需要唔同嘅學習策略，find out你嘅best way of learning.'},
  {'audio': './audio/1599.wav',
   'text': 'language Cantonese<asr_text>神經肌肉體能訓練（Neuromuscular Training)能夠提升你嘅reaction speed，增加對衝擊力嘅resistance，係種prevent injury嘅training method。'},
  {'audio': './audio/1538.wav',
   'text': 'language Cantonese<asr_text>Prepare嚟唔怕，對於exam一定要溫完書，進咗考場先至relax啲。'},
  {'audio': './audio/1405.wav',
   'text': 'language Cantonese<asr_text>我成日喺YouTube explore下新嘅music videos，keep我self updated.'},
  {'audio': './audio/1650.wav',
   'text': 'language Cantonese<asr_text>Surprise噶，今晚居然有meteor shower，赶紧去rooftop睇吓啊。'},
  {'audio': './audio/327.wav',
   'text': 'language Cantonese<asr_text>我喺department store見到一件好靚嘅dress，但我覺得價錢有啲expensive，邊款比較值得買呢？'},
  {'audio': './audio/442.wav',
   'text': 'language Cantonese<asr_text>面對困難唔好放棄，只要keep going，想成功就一定會有way out。”'},
  {'audio': './audio/774.wav',
   'text': 'language Cantonese<asr_text>Football game嘅excitement同激情，係其他活動難以match得爾。'},
  {'audio': './audio/1087.wav',
   'text': 'language Cantonese<asr_text>學習並唔係要爭第一，重要嘅是學識appreciate知識帶嚟嘅樂趣。'},
  {'audio': './audio/1220.wav',
   'text': 'language Cantonese<asr_text>假日我鍾意去concert，感受現場音樂嘅dynamic，每次都係一個unforgettable嘅experience。'},
  {'audio': './audio/1635.wav',
   'text': 'language Cantonese<asr_text>Respect嘅culture可以俾到你个good working environment同埋improve job satisfaction.'},
  {'audio': './audio/177.wav',
   'text': 'language Cantonese<asr_text>天氣預報話會有heavy rain，出門前記得carry傘喇。'},
  {'audio': './audio/1322.wav',
   'text': 'language Cantonese<asr_text>如果要improve咁嘅physical fitness，可以regular咁去gym或者自己做home workout。'},
  {'audio': './audio/704.wav',
   'text': "language Cantonese<asr_text>我鍾意去outlet買嘢，因為通常都會have some really nice deals，如果you're lucky 的話。"},
  {'audio': './audio/86.wav',
   'text': 'language Cantonese<asr_text>喺天氣app度睇到今晚可能會有heavy rain，大家出門記得帶umbrella呀。'},
  {'audio': './audio/1883.wav',
   'text': 'language Cantonese<asr_text>元朗大棠路有個organic farm我成日喺度買food，你可以去贏咗啲便利店嗰啲！'},
  {'audio': './audio/1947.wav',
   'text': 'language Cantonese<asr_text>每次聽K-pop嘅時候，我就會feel得好興奮，跟住音樂擺動箇身，好舒服呀。'},
  {'audio': './audio/457.wav',
   'text': 'language Cantonese<asr_text>我最愛嘅steak tartare，喺raw嘅感覺同新鮮嘅taste之間做到一個完美嘅balance!"  '},
  {'audio': './audio/1828.wav',
   'text': 'language Cantonese<asr_text>今日嘅Weather好Perfect，希望明日都能持續Keep it up。'},
  {'audio': './audio/54.wav',
   'text': 'language Cantonese<asr_text>我記得剛才聽新聞話，佢哋提出新建商業district嘅proposal，我覺得呢個可行，可以boost本地經濟。'},
  {'audio': './audio/1501.wav',
   'text': 'language Cantonese<asr_text>Hiking唔單止可以appreciate到nature嘅美，亦可以提升你嘅cardiovascular health。'},
  {'audio': './audio/643.wav',
   'text': 'language Cantonese<asr_text>今天嘅weather forecast predict会有大雪，希望唔需要去返工就nice!'},
  {'audio': './audio/677.wav',
   'text': 'language Cantonese<asr_text>我鐘意去concert feel到現場嘅energy，尤其喺EDM嗰dshow，真係好震撼！'},
  {'audio': './audio/221.wav',
   'text': 'language Cantonese<asr_text>我嘅朋友推薦我試下kick boxing, 佢話可以幫助保持active lifestyle。'},
  {'audio': './audio/113.wav',
   'text': 'language Cantonese<asr_text>France嘅cuisine大家都識，但如果當地嘅cooking class就未必咁簡單，但我想嘗試下，肯定好fun架！'},
  {'audio': './audio/982.wav',
   'text': 'language Cantonese<asr_text>Political stability喺香港令人擔憂，我哋需要透明同公平嘅政治制度。'},
  {'audio': './audio/1228.wav',
   'text': 'language Cantonese<asr_text>游水係一個full-body workout，可以同時train到我哋嘅upper body同lower body。'},
  {'audio': './audio/999.wav',
   'text': 'language Cantonese<asr_text>學習唔會有end point, 一直keep learning 會比我哋多元嘅perspectives。'},
  {'audio': './audio/174.wav',
   'text': 'language Cantonese<asr_text>有時候work會變得tough，但記住唔可以give up easily，有determination係必要嘅。'},
  {'audio': './audio/781.wav',
   'text': 'language Cantonese<asr_text>Boxing 唔只需要powerful punches, 而且要有quick reflexes同埋strategic思維，係一種full body workout。'},
  {'audio': './audio/589.wav',
   'text': 'language Cantonese<asr_text>睇緊世界盃，都令我觸動起good sportsmanship和team spirit 嘅重要性。'},
  {'audio': './audio/1559.wav',
   'text': 'language Cantonese<asr_text>今天呢，feel到蛮humid，呢D室外活动可能会feel好sweaty嘅。'},
  {'audio': './audio/18.wav',
   'text': 'language Cantonese<asr_text>打邊爐就係我冬天嘅favourite comfort food，我鍾意邊食邊同friend嗑嗑牙，攞嚟驅寒實在冇得頂。'},
  {'audio': './audio/423.wav',
   'text': 'language Cantonese<asr_text>我買咗一對vintage jeans，好岩我嘅style，就算佢cost我一筆錢，我都覺得值得，因為我真係好like呢條jeans呀！'},
  {'audio': './audio/1343.wav',
   'text': 'language Cantonese<asr_text>Uniqlo嘅Heattech衫新色出咗，準備買幾件應付寒冬，保暖又時尚咁！'},
  {'audio': './audio/285.wav',
   'text': 'language Cantonese<asr_text>我老公煮嘅fried beehoon超級delicious，好食到我想睇佢埋廚神秘境界同佢學science咁！'},
  {'audio': './audio/1583.wav',
   'text': 'language Cantonese<asr_text>我通常喺nightclub度過我嘅夜晚，跳下舞，享受下音樂嘅Vibes.'},
  {'audio': './audio/428.wav',
   'text': 'language Cantonese<asr_text>Remember，唔要怕出錯，因為mistakes係學習嘅一部分。" '},
  {'audio': './audio/1509.wav',
   'text': 'language Cantonese<asr_text>Cycling喺一個健康同好玩嘅way，可以exploring返你嘅周邊環境同埋keep fit。'},
  {'audio': './audio/1318.wav',
   'text': 'language Cantonese<asr_text>如果你想減肥，可以try out intermittent fasting或者low carbs diet，但最重要嘅係maintain一個healthy lifestyle，包括練習運動。'},
  {'audio': './audio/669.wav',
   'text': 'language Cantonese<asr_text>\'"新加坡嘅Merlion Park真系好cool，我喺度嘅experience我会记住一世！"\''},
  {'audio': './audio/31.wav',
   'text': "language Cantonese<asr_text>我個weekend去睇咗'The Avengers'嘅movie，電影咁intense，真係我今年睇過最好嘅show。"},
  {'audio': './audio/940.wav',
   'text': 'language Cantonese<asr_text>我煮嘅curry chicken煲仔飯，用咗coconut milk同大量嘅spices，super aromatic，一試就會fall in love!'},
  {'audio': './audio/722.wav',
   'text': 'language Cantonese<asr_text>我哋嘅target係提升productivity，改善workflow，並且maximize嘅profits.'},
  {'audio': './audio/994.wav',
   'text': 'language Cantonese<asr_text>勤力嘅 study 會俾我哋帶來成果，但唔好ignore身體嘅genuine needs。'},
  {'audio': './audio/214.wav',
   'text': 'language Cantonese<asr_text>我小時候最鍾意去theme park，玩過山車，每次都覺得scream out loud，真係超exciting。'},
  {'audio': './audio/813.wav',
   'text': 'language Cantonese<asr_text>透過參加各種workshop同培訓，我哋可以繼續學習新skill同增強個人競爭力。'},
  {'audio': './audio/326.wav',
   'text': 'language Cantonese<asr_text>我今日就去一個大sale，想買個brand new嘅handbag，好期待呢！'},
  {'audio': './audio/560.wav',
   'text': 'language Cantonese<asr_text>我鍾意嗰間cafe嘅brunch嘅時候，最愛點嗮荷包蛋、煙三文魚同粟米餅，味道就嚟好fantastic!'},
  {'audio': './audio/1112.wav',
   'text': 'language Cantonese<asr_text>近期嘅UV Index真係太高，隔热系做得唔好，feel得成日皮肤都為住sunburn喺受罪。'},
  {'audio': './audio/700.wav',
   'text': 'language Cantonese<asr_text>政府應積極甄別技能短缺，透過Education reform 提高工人嘅技能，促進經濟發展。'},
  {'audio': './audio/1578.wav',
   'text': 'language Cantonese<asr_text>喺Thailand嘅Bangkok 嘅street markets 行過，一定會覺得好vibrant 嘅cultural experience！'},
  {'audio': './audio/1189.wav',
   'text': 'language Cantonese<asr_text>话说下个weekend嘅climate真係令人期待，据说会有连晴数日，就算唔出门，喺屋企都可以feel到质次sunshine。'},
  {'audio': './audio/341.wav',
   'text': 'language Cantonese<asr_text>學識學嘢唔只係讀書，還要learn from experience啦，這種事好common架。'},
  {'audio': './audio/629.wav',
   'text': 'language Cantonese<asr_text>健康係樣商數，無論你點鐘work ，都要計返自己嘅health。'},
  {'audio': './audio/147.wav',
   'text': 'language Cantonese<asr_text>我仲鐘意喺online stores 買fashion accessories，帶埋我嘅outfits，feel more stylish同埋fashionable。'},
  {'audio': './audio/1309.wav',
   'text': 'language Cantonese<asr_text>如果你問我喜不喜歡做yoga，我會話你我每日都會spend一小時在家練習，好欣賞佢帶來嘅relaxation.'},
  {'audio': './audio/360.wav',
   'text': 'language Cantonese<asr_text>去迎接快要arrive嘅spring吧，花应该准备再bloom喇。'},
  {'audio': './audio/83.wav',
   'text': 'language Cantonese<asr_text>我每天都set咗一個to-do list，咁樣我先可以manage我嘅時間，做到最efficient嘅工作。'},
  {'audio': './audio/48.wav',
   'text': 'language Cantonese<asr_text>我見到報導話佢哋準備implement新嘅rent control policy，我覺得咁樣好保護住住客，但都怕有negative side effects喺房東身上。'},
  {'audio': './audio/468.wav',
   'text': 'language Cantonese<asr_text>去年喺Japan嘅Tokyo shopping真系玩得好过癮，今年我想再去一次咋！'},
  {'audio': './audio/155.wav',
   'text': 'language Cantonese<asr_text>我鐘意逛市集，可以睇到一啲handmade crafts，可以support local artists，真係meaningful。'},
  {'audio': './audio/772.wav',
   'text': 'language Cantonese<asr_text>Cycling唔只係一种sport，佢更係一個way of life，我哋可以享受清新嘅air 和美丽嘅scenery。'},
  {'audio': './audio/1239.wav',
   'text': 'language Cantonese<asr_text>香港嘅Air pollution 問題嚴重，我哋需要promote more renewable energy sources。'},
  {'audio': './audio/1200.wav',
   'text': 'language Cantonese<asr_text>经常去嘅流动面档就系吾可以錯过，客人拎个电子菜单首先mark咗想要嘅ingredients，然后等待佢哋炒出嚟，热辣辣、fresh and tasty。'},
  {'audio': './audio/1402.wav',
   'text': 'language Cantonese<asr_text>之後呢，我好enjoy去karaoke night, 跟埋friend sing一sing我地最鐘意嘅songs。”'},
  {'audio': './audio/1202.wav',
   'text': 'language Cantonese<asr_text>我冇抗拒到嘅dessert就系mango sago，sweet mango juice同粒粒香脆嘅西米一混合，好似春日嘅爽滑风情，让人in love喎！'},
  {'audio': './audio/1630.wav',
   'text': 'language Cantonese<asr_text>唔好睇低self-learning嘅力量，independent study都係好重要嘅学习技巧。'},
  {'audio': './audio/500.wav',
   'text': 'language Cantonese<asr_text>本地短缺創新科技人才，学校應該more focus on STEM education。'},
  {'audio': './audio/1764.wav',
   'text': 'language Cantonese<asr_text>食完飯之後，一家人喺家睇下Netflix，一齊笑，一齊驚，真係超warm.'},
  {'audio': './audio/179.wav',
   'text': 'language Cantonese<asr_text>今日會好cold，記得穿多件sweater出門啊。'},
  {'audio': './audio/1047.wav',

In [25]:
# trainDF = pd.read_json("train_raw.jsonl", lines=True)

# print(trainDF.head())
# print(trainDF.columns)  # Should show: ['audio', 'text', 'ref_audio']

In [26]:
# trainDF

In [27]:
# trainDF["ref_audio"][0]

### # Download model into local Directory

In [28]:
# Using huggingface-cli (install if needed: pip install -U huggingface_hub[cli])

# !huggingface-cli download Qwen/Qwen3-ASR-1.7B --local-dir ./Qwen3-ASR-1.7B
!huggingface-cli download Qwen/Qwen3-ASR-0.6B --local-dir ./Qwen3-ASR-0.6B

⚠️  Warning: 'huggingface-cli download' is deprecated. Use 'hf download' instead.
Fetching 10 files:   0%|                                 | 0/10 [00:00<?, ?it/s]Downloading 'model.safetensors' to 'Qwen3-ASR-0.6B/.cache/huggingface/download/xGOKKLRSlIhH692hSVvI1-gpoa8=.79d6cbd4c98c7bbffe9db2edac07f56cd6637d0d5944b27f6c2b8353840323ea.incomplete'

model.safetensors:   0%|                            | 0.00/1.88G [00:00<?, ?B/s]Downloading 'chat_template.json' to 'Qwen3-ASR-0.6B/.cache/huggingface/download/BqEbVjUtvDkrcHAfaoo906xJg7Y=.c44736493efd71ec96218cc626904698cdb13235.incomplete'
Downloading 'preprocessor_config.json' to 'Qwen3-ASR-0.6B/.cache/huggingface/download/PYH5dHjks7Ei0Yd3X0Z8xIwsCNQ=.8f7f07346466d5d494ec0d4969d1c3d0190eed72.incomplete'
Downloading 'config.json' to 'Qwen3-ASR-0.6B/.cache/huggingface/download/8_PA_wEVGiVa2goH2H4KQOQpvVY=.8113d596dec2d1a2ef4552edfe005ee84d16d9ec.incomplete'
Downloading '.gitattributes' to 'Qwen3-ASR-0.6B/.cache/huggingface/download/wPaCkH-WbT7GsmxMKKrNZTV4nSM=.a6344aac8c09253b3b630fb776ae94478aa0275b.incomplete'
Downloading 'generation_config.json' to 'Qwen3-ASR-0.6B/.cache/huggingface/download/3EVKVggOldJcKSsGjSdoUCN1AyQ=.7382a4d347c0a865b76bb1b8277f66a5ac312854.incomplete'
Downloading 'merges.txt' to 'Qwen3-ASR-0.6B/.cache/huggingface/download/PtHk0z_I45atnj23IIRhTExwT3w=.31349551d90c7606f325fe0f11bbb8bd5fa0d7c7.incomplete'
Downloading 'README.md' to 'Qwen3-ASR-0.6B/.cache/huggingface/download/Xn7B-BWUGOee2Y6hCZtEhtFu4BE=.3a67d43f21febda213ff36efdb60ef10019af7f3.incomplete'


preprocessor_config.json: 100%|████████████████| 330/330 [00:00<00:00, 1.32MB/s]


Download complete. Moving file to Qwen3-ASR-0.6B/preprocessor_config.json
.gitattributes: 0.00B [00:00, ?B/s]


chat_template.json: 0.00B [00:00, ?B/s]



generation_config.json: 100%|███████████████████| 142/142 [00:00<00:00, 615kB/s]
chat_template.json: 1.16kB [00:00, 470kB/s]
Download complete. Moving file to Qwen3-ASR-0.6B/generation_config.json
.gitattributes: 1.52kB [00:00, 345kB/s]Download complete. Moving file to Qwen3-ASR-0.6B/chat_template.json

Download complete. Moving file to Qwen3-ASR-0.6B/.gitattributes


README.md: 0.00B [00:00, ?B/s]


Fetching 10 files:  10%|██▌                      | 1/10 [00:01<00:09,  1.09s/it]



config.json: 6.19kB [00:00, 2.75MB/s]A
Download complete. Moving file to Qwen3-ASR-0.6B/config.json
README.md: 57.5kB [00:00, 5.89MB/s]
Download complete. Moving file to Qwen3-ASR-0.6B/README.md



merges.txt: 582kB [00:00, 5.79MB/s]


merges.txt: 1.67MB [00:00, 6.13MB/s]
Download complete. Moving file to Qwen3-ASR-0.6B/merges.txt
Fetching 10 files:  60%|███████████████          | 6/10 [00:01<00:00,  5.50it/s]Downloading 'vocab.json' to 'Qwen3-ASR-0.6B/.cache/huggingface/download/j3m-Hy6QvBddw8RXA1uSWl1AJ0c=.4783fe10ac3adce15ac8f358ef5462739852c569.incomplete'
Downloading 'tokenizer_config.json' to 'Qwen3-ASR-0.6B/.cache/huggingface/download/vzaExXFZNBay89bvlQv-ZcI6BTg=.b93109843922a40c6654c5449d3bf95372267c66.incomplete'


tokenizer_config.json: 12.5kB [00:00, 22.0MB/s]A
Download complete. Moving file to Qwen3-ASR-0.6B/tokenizer_config.json


vocab.json: 0.00B [00:00, ?B/s]

vocab.json: 991kB [00:00, 9.90MB/s]

vocab.json: 2.78MB [00:00, 10.7MB/s]
Download complete. Moving file to Qwen3-ASR-0.6B/vocab.json

model.safetensors:   0%|                            | 0.00/1.88G [00:01<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:02<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:02<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:02<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:02<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:02<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:02<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:02<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:02<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:02<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:03<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:03<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:03<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:03<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:03<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:03<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:03<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:03<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:03<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:04<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:04<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:04<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:04<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:04<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:04<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:04<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:04<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:04<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:04<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:04<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:05<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:05<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:05<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:05<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:05<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:05<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:05<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:05<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:05<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:05<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:05<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:05<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:06<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:06<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:06<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:06<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:06<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:06<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:06<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:06<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:06<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:06<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:06<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:07<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:07<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:07<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:07<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:07<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:07<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:07<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:07<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:07<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:07<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:08<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:08<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:08<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:08<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:08<?, ?B/s]
model.safetensors:   0%|                            | 0.00/1.88G [00:08<?, ?B/s]
Fetching 10 files:  60%|███████████████          | 6/10 [00:19<00:00,  5.50it/s]
model.safetensors:   4%|▋                   | 67.1M/1.88G [00:19<00:02, 644MB/s]
model.safetensors:  14%|██▊                 | 268M/1.88G [00:51<04:39, 5.76MB/s]
model.safetensors:  14%|██▊                 | 268M/1.88G [00:51<05:13, 5.12MB/s]
model.safetensors:  25%|█████               | 469M/1.88G [01:01<03:05, 7.60MB/s]
model.safetensors:  42%|████████▎           | 781M/1.88G [01:07<01:24, 13.0MB/s]
model.safetensors:  42%|████████▎           | 781M/1.88G [01:19<01:24, 13.0MB/s]
model.safetensors:  45%|█████████           | 848M/1.88G [01:37<04:36, 3.72MB/s]
model.safetensors:  45%|█████████           | 848M/1.88G [01:37<04:36, 3.72MB/s]
model.safetensors:  45%|█████████           | 848M/1.88G [01:37<04:36, 3.72MB/s]
model.safetensors:  45%|█████████           | 848M/1.88G [01:37<04:36, 3.72MB/s]
model.safetensors:  45%|█████████           | 848M/1.88G [01:49<04:36, 3.72MB/s]
model.safetensors:  56%|██████████▌        | 1.05G/1.88G [01:52<01:08, 12.1MB/s]
model.safetensors:  56%|██████████▌        | 1.05G/1.88G [01:52<01:08, 12.1MB/s]
model.safetensors:  56%|██████████▌        | 1.05G/1.88G [01:52<01:08, 12.1MB/s]
model.safetensors:  56%|██████████▌        | 1.05G/1.88G [01:52<01:08, 12.1MB/s]
model.safetensors:  56%|██████████▌        | 1.05G/1.88G [01:52<01:08, 12.1MB/s]
model.safetensors:  56%|██████████▌        | 1.05G/1.88G [01:52<01:08, 12.1MB/s]
model.safetensors:  56%|██████████▌        | 1.05G/1.88G [01:52<01:08, 12.1MB/s]
model.safetensors:  59%|███████████▎       | 1.12G/1.88G [02:01<01:08, 11.0MB/s]
model.safetensors:  59%|███████████▎       | 1.12G/1.88G [02:01<01:21, 9.34MB/s]
model.safetensors:  59%|███████████▎       | 1.12G/1.88G [02:01<01:21, 9.34MB/s]
model.safetensors:  63%|███████████▉       | 1.18G/1.88G [02:04<01:04, 10.8MB/s]
model.safetensors:  77%|██████████████▋    | 1.45G/1.88G [02:07<00:20, 20.8MB/s]
model.safetensors:  77%|██████████████▋    | 1.45G/1.88G [02:07<00:04, 97.8MB/s]
model.safetensors:  77%|██████████████▋    | 1.45G/1.88G [02:07<00:04, 97.8MB/s]
model.safetensors:  77%|██████████████▋    | 1.45G/1.88G [02:07<00:04, 97.8MB/s]
model.safetensors:  77%|██████████████▋    | 1.45G/1.88G [02:07<00:04, 97.8MB/s]
model.safetensors:  77%|██████████████▋    | 1.45G/1.88G [02:07<00:04, 97.8MB/s]
model.safetensors:  77%|██████████████▋    | 1.45G/1.88G [02:07<00:04, 97.8MB/s]
model.safetensors:  77%|██████████████▋    | 1.45G/1.88G [02:07<00:04, 97.8MB/s]
model.safetensors:  77%|██████████████▋    | 1.45G/1.88G [02:07<00:04, 97.8MB/s]
model.safetensors:  77%|██████████████▋    | 1.45G/1.88G [02:07<00:04, 97.8MB/s]
model.safetensors:  77%|██████████████▋    | 1.45G/1.88G [02:07<00:04, 97.8MB/s]
model.safetensors:  77%|██████████████▋    | 1.45G/1.88G [02:07<00:04, 97.8MB/s]
model.safetensors:  77%|██████████████▋    | 1.45G/1.88G [02:07<00:04, 97.8MB/s]
model.safetensors:  81%|████████████████▏   | 1.52G/1.88G [02:07<00:03, 107MB/s]
model.safetensors:  84%|████████████████▉   | 1.59G/1.88G [02:07<00:01, 149MB/s]
model.safetensors:  84%|████████████████▉   | 1.59G/1.88G [02:07<00:01, 149MB/s]
model.safetensors:  84%|████████████████▉   | 1.59G/1.88G [02:07<00:01, 149MB/s]
model.safetensors:  84%|████████████████▉   | 1.59G/1.88G [02:07<00:01, 149MB/s]
model.safetensors:  88%|████████████████▋  | 1.65G/1.88G [02:10<00:03, 67.5MB/s]
model.safetensors:  92%|█████████████████▍ | 1.72G/1.88G [02:16<00:05, 29.0MB/s]
model.safetensors:  95%|██████████████████ | 1.79G/1.88G [02:18<00:02, 30.2MB/s]
model.safetensors:  95%|██████████████████ | 1.79G/1.88G [02:18<00:02, 31.2MB/s]
model.safetensors: 100%|███████████████████| 1.88G/1.88G [02:19<00:00, 13.4MB/s]
Download complete. Moving file to Qwen3-ASR-0.6B/model.safetensors
Fetching 10 files: 100%|████████████████████████| 10/10 [02:20<00:00, 14.06s/it]
/home/aifather/qwen3-asr-hk-cantonese-finetune/Dataset-Cantonese-Training/Qwen3-ASR-0.6B

# Run Prepare data script from Qwen3 fine turning python script)

In [32]:
%%time 
# ## Support generate both train and evaluate 
# !python prepare_train_evaluate_data.py \
# --device cuda:0 \
# --input_jsonl train_raw.jsonl \
# --output_train_jsonl train_prepared.jsonl \
# --output_eval_jsonl eval_prepared.jsonl \
# --eval_ratio 0.1 \
# --speaker_name hk_cantonese_speaker
# !python prepare_train_dataset.py

CPU times: user 11 μs, sys: 2 μs, total: 13 μs
Wall time: 25.7 μs

# Run SFT using the prepared JSONL:
#### select batch size depend on your gpu memory: minimize at least GPU 12GB VRAM, otherwise error Out-of-Memory (OOM)
#### batch _size =1 or 2 for 12GB (3080 GPU),  batch_size =4 for 16GB GPU VRAM

### MLflow Trace support version

In [30]:
%%time
# !python sft_12hz_mlflow.py \
#   --init_model_path ./Qwen3-TTS-12Hz-0.6B-Base \
#   --output_model_path output \
#   --train_jsonl train_prepared.jsonl \
#   --batch_size 2 \
#   --lr 1e-5 \
#   --num_epochs 20 \
#   --gradient_accumulation_steps 8 \
#   --speaker_name speaker_test \
#   --mlflow_tracking_uri http://localhost:5000

CPU times: user 11 μs, sys: 2 μs, total: 13 μs
Wall time: 25.5 μs

In [50]:
# upload final model to mlflow
import mlflow
# mlflow.log_artifacts("output/checkpoint-epoch-3", artifact_path="final_checkpoint")

## Test Qwen3 Pre-train model performance

In [74]:
%%time
!python evaluate_qwen3_asr.py \
  --checkpoint_dir ./Qwen3-ASR-0.6B \
  --test_jsonl  val.jsonl \
  --output_dir ./asr_evaluation_results_pretrained \
  --language Cantonese \
  --max_samples 500

Loading Qwen3-ASR from: ./Qwen3-ASR-0.6B
The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
✅ Loaded 500 test samples
🚀 Starting evaluation with MANUAL WER/CER (custom tokenizer)...

Evaluating:   0%|                                   | 0/500 [00:00<?, ?sample/s]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   0%|                           | 1/500 [00:02<19:53,  2.39s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   0%|                           | 2/500 [00:03<15:07,  1.82s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   1%|▏                          | 3/500 [00:04<12:31,  1.51s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   1%|▏                          | 4/500 [00:05<10:56,  1.32s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   1%|▎                          | 5/500 [00:07<11:47,  1.43s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   1%|▎                          | 6/500 [00:09<12:30,  1.52s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   1%|▍                          | 7/500 [00:11<14:11,  1.73s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   2%|▍                          | 8/500 [00:12<13:19,  1.63s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   2%|▍                          | 9/500 [00:14<14:21,  1.75s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   2%|▌                         | 10/500 [00:16<14:04,  1.72s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   2%|▌                         | 11/500 [00:18<13:48,  1.69s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   2%|▌                         | 12/500 [00:19<12:23,  1.52s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   3%|▋                         | 13/500 [00:20<12:10,  1.50s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   3%|▋                         | 14/500 [00:22<12:32,  1.55s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   3%|▊                         | 15/500 [00:23<12:29,  1.54s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   3%|▊                         | 16/500 [00:25<13:03,  1.62s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   3%|▉                         | 17/500 [00:27<14:21,  1.78s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   4%|▉                         | 18/500 [00:29<13:55,  1.73s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   4%|▉                         | 19/500 [00:30<11:52,  1.48s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   4%|█                         | 20/500 [00:31<11:14,  1.40s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   4%|█                         | 21/500 [00:33<12:24,  1.55s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   4%|█▏                        | 22/500 [00:35<12:32,  1.57s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   5%|█▏                        | 23/500 [00:36<12:34,  1.58s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   5%|█▏                        | 24/500 [00:38<12:15,  1.55s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   5%|█▎                        | 25/500 [00:39<11:47,  1.49s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   5%|█▎                        | 26/500 [00:40<11:31,  1.46s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   5%|█▍                        | 27/500 [00:43<13:23,  1.70s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   6%|█▍                        | 28/500 [00:45<14:28,  1.84s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   6%|█▌                        | 29/500 [00:46<13:37,  1.74s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   6%|█▌                        | 30/500 [00:48<13:11,  1.68s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   6%|█▌                        | 31/500 [00:49<11:26,  1.46s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   6%|█▋                        | 32/500 [00:50<10:41,  1.37s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   7%|█▋                        | 33/500 [00:52<12:22,  1.59s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   7%|█▊                        | 34/500 [00:53<10:58,  1.41s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   7%|█▊                        | 35/500 [00:54<10:30,  1.36s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   7%|█▊                        | 36/500 [00:56<10:08,  1.31s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   7%|█▉                        | 37/500 [00:58<11:28,  1.49s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   8%|█▉                        | 38/500 [00:59<10:55,  1.42s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   8%|██                        | 39/500 [01:00<10:42,  1.39s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   8%|██                        | 40/500 [01:01<10:23,  1.36s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   8%|██▏                       | 41/500 [01:04<12:44,  1.66s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   8%|██▏                       | 42/500 [01:05<12:39,  1.66s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   9%|██▏                       | 43/500 [01:07<12:26,  1.63s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   9%|██▎                       | 44/500 [01:08<11:59,  1.58s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   9%|██▎                       | 45/500 [01:10<12:59,  1.71s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   9%|██▍                       | 46/500 [01:11<11:05,  1.47s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:   9%|██▍                       | 47/500 [01:13<11:56,  1.58s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  10%|██▍                       | 48/500 [01:15<11:53,  1.58s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  10%|██▌                       | 49/500 [01:16<12:02,  1.60s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  10%|██▌                       | 50/500 [01:19<13:48,  1.84s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  10%|██▋                       | 51/500 [01:20<12:22,  1.65s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  10%|██▋                       | 52/500 [01:22<12:31,  1.68s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  11%|██▊                       | 53/500 [01:23<12:17,  1.65s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  11%|██▊                       | 54/500 [01:25<12:14,  1.65s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  11%|██▊                       | 55/500 [01:26<11:44,  1.58s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  11%|██▉                       | 56/500 [01:28<10:44,  1.45s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  11%|██▉                       | 57/500 [01:29<10:18,  1.40s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  12%|███                       | 58/500 [01:30<09:54,  1.35s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  12%|███                       | 59/500 [01:32<11:19,  1.54s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  12%|███                       | 60/500 [01:33<10:56,  1.49s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  12%|███▏                      | 61/500 [01:35<11:02,  1.51s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  12%|███▏                      | 62/500 [01:37<11:05,  1.52s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  13%|███▎                      | 63/500 [01:38<11:27,  1.57s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  13%|███▎                      | 64/500 [01:39<10:23,  1.43s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  13%|███▍                      | 65/500 [01:40<09:16,  1.28s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  13%|███▍                      | 66/500 [01:42<09:37,  1.33s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  13%|███▍                      | 67/500 [01:43<09:11,  1.27s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  14%|███▌                      | 68/500 [01:45<10:19,  1.43s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  14%|███▌                      | 69/500 [01:46<10:37,  1.48s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  14%|███▋                      | 70/500 [01:48<10:39,  1.49s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  14%|███▋                      | 71/500 [01:49<09:49,  1.37s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  14%|███▋                      | 72/500 [01:50<09:26,  1.32s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  15%|███▊                      | 73/500 [01:52<09:59,  1.40s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  15%|███▊                      | 74/500 [01:53<10:37,  1.50s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  15%|███▉                      | 75/500 [01:55<10:12,  1.44s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  15%|███▉                      | 76/500 [01:56<09:23,  1.33s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  15%|████                      | 77/500 [01:57<09:00,  1.28s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  16%|████                      | 78/500 [01:58<08:11,  1.16s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  16%|████                      | 79/500 [02:00<09:39,  1.38s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  16%|████▏                     | 80/500 [02:00<08:27,  1.21s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  16%|████▏                     | 81/500 [02:02<09:20,  1.34s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  16%|████▎                     | 82/500 [02:05<11:44,  1.69s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  17%|████▎                     | 83/500 [02:06<11:32,  1.66s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  17%|████▎                     | 84/500 [02:08<11:02,  1.59s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  17%|████▍                     | 85/500 [02:09<11:17,  1.63s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  17%|████▍                     | 86/500 [02:11<11:04,  1.61s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  17%|████▌                     | 87/500 [02:13<11:27,  1.66s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  18%|████▌                     | 88/500 [02:15<11:44,  1.71s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  18%|████▋                     | 89/500 [02:17<12:12,  1.78s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  18%|████▋                     | 90/500 [02:18<10:47,  1.58s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  18%|████▋                     | 91/500 [02:19<09:49,  1.44s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  18%|████▊                     | 92/500 [02:20<09:54,  1.46s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  19%|████▊                     | 93/500 [02:22<09:49,  1.45s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  19%|████▉                     | 94/500 [02:24<10:40,  1.58s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  19%|████▉                     | 95/500 [02:25<10:48,  1.60s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  19%|████▉                     | 96/500 [02:27<11:07,  1.65s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  19%|█████                     | 97/500 [02:28<09:17,  1.38s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  20%|█████                     | 98/500 [02:29<09:22,  1.40s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  20%|█████▏                    | 99/500 [02:31<10:18,  1.54s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  20%|█████                    | 100/500 [02:32<09:58,  1.50s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  20%|█████                    | 101/500 [02:34<09:22,  1.41s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  20%|█████                    | 102/500 [02:35<09:04,  1.37s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  21%|█████▏                   | 103/500 [02:36<08:56,  1.35s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  21%|█████▏                   | 104/500 [02:38<08:51,  1.34s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  21%|█████▎                   | 105/500 [02:39<09:49,  1.49s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  21%|█████▎                   | 106/500 [02:41<09:53,  1.51s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  21%|█████▎                   | 107/500 [02:43<10:08,  1.55s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  22%|█████▍                   | 108/500 [02:44<10:45,  1.65s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  22%|█████▍                   | 109/500 [02:46<10:25,  1.60s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  22%|█████▌                   | 110/500 [02:47<08:59,  1.38s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  22%|█████▌                   | 111/500 [02:48<09:34,  1.48s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  22%|█████▌                   | 112/500 [02:51<10:49,  1.67s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  23%|█████▋                   | 113/500 [02:52<11:10,  1.73s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  23%|█████▋                   | 114/500 [02:54<10:55,  1.70s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  23%|█████▊                   | 115/500 [02:55<09:18,  1.45s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  23%|█████▊                   | 116/500 [02:56<09:14,  1.44s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  23%|█████▊                   | 117/500 [02:58<09:25,  1.48s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  24%|█████▉                   | 118/500 [02:59<09:12,  1.45s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  24%|█████▉                   | 119/500 [03:01<10:04,  1.59s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  24%|██████                   | 120/500 [03:03<10:17,  1.63s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  24%|██████                   | 121/500 [03:04<09:48,  1.55s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  24%|██████                   | 122/500 [03:06<09:39,  1.53s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  25%|██████▏                  | 123/500 [03:07<09:13,  1.47s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  25%|██████▏                  | 124/500 [03:08<08:47,  1.40s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  25%|██████▎                  | 125/500 [03:10<09:32,  1.53s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  25%|██████▎                  | 126/500 [03:12<09:27,  1.52s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Evaluating:  25%|██████▎                  | 127/500 [03:14<10:10,  1.64s/sample]Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.

## Read Result

In [76]:
evalResultFile= "./asr_evaluation_results_pretrained/results.csv"

In [77]:
evalResultDF = pd.read_csv(evalResultFile)
evalResultDF

,index,ref_text,pred_text,cer,wer,rtf,audio_duration_sec,inference_time_sec,ref_words_array,pred_words_array,...,wer_insertions,wer_errors_(S+D+I),ref_chars_array,pred_chars_array,ref_chars,cer_substitutions,cer_deletions,cer_insertions,cer_errors_(S+D+I),audio
0,0,做yoga可以改善你的flexibility，同時亦能提升你的inner peace和focus.,做 yoga 可以改善你嘅 flexibility，同時亦能提升你的 inner peace...,0.1633,0.2000,0.2415,9.899,2.3907,"做, yoga, 可以改善你的, flexibility, ，同時亦能提升你的, inner...","做, yoga, 可以改善你嘅, flexibility, ，同時亦能提升你的, inner...",...,0,2,"做, y, o, g, a, 可, 以, 改, 善, 你, 的, f, l, e, x, i...","做, , y, o, g, a, , 可, 以, 改, 善, 你, 嘅, , f, l...",49,2,0,6,8,./audio/1860.wav
1,1,每日都要set新嘅goals，並keep track嘅progress，咁先可以開展自己嘅p...,每日都要set新嘅goals並keep track嘅progress，咁先可以開展自己嘅po...,0.0182,0.0833,0.2321,6.123,1.4212,"每日都要, set, 新嘅, goals, ，並, keep, track, 嘅, prog...","每日都要, set, 新嘅, goals, 並, keep, track, 嘅, progr...",...,0,1,"每, 日, 都, 要, s, e, t, 新, 嘅, g, o, a, l, s, ，, 並...","每, 日, 都, 要, s, e, t, 新, 嘅, g, o, a, l, s, 並, k...",55,0,1,0,1,./audio/353.wav
2,2,香港嘅public transport system 需要更多嘅improvements去減...,但public transport system需要更多嘅improvement，係減逼co...,0.1207,0.3333,0.3150,3.627,1.1423,"香港嘅, public, transport, system, 需要更多嘅, improve...","但, public, transport, system, 需要更多嘅, improveme...",...,0,3,"香, 港, 嘅, p, u, b, l, i, c, , t, r, a, n, s, p...","但, p, u, b, l, i, c, , t, r, a, n, s, p, o, r...",58,4,3,0,7,./audio/1333.wav
3,3,透過學習，我哋可以empower自己去迎接新嘅challenges。,透過學習，我哋可以empower自己去迎接新嘅challenge。,0.0294,0.2000,0.2933,3.520,1.0323,"透過學習，我哋可以, empower, 自己去迎接新嘅, challenges, 。","透過學習，我哋可以, empower, 自己去迎接新嘅, challenge, 。",...,0,1,"透, 過, 學, 習, ，, 我, 哋, 可, 以, e, m, p, o, w, e, r...","透, 過, 學, 習, ，, 我, 哋, 可, 以, e, m, p, o, w, e, r...",34,0,1,0,1,./audio/905.wav
4,4,趁热食意粉，搞两粒鸡蛋，runny yolk滴落去，滑inh到can't stop！,親要食意粉，攪兩碌雞蛋，rainy york滴落去，或inch到count stop。,0.3571,0.7778,0.2419,6.677,1.6152,"趁热食意粉，搞两粒鸡蛋，, runny, yolk, 滴落去，滑, inh, 到, can'...","親要食意粉，攪兩碌雞蛋，, rainy, york, 滴落去，或, inch, 到, cou...",...,0,7,"趁, 热, 食, 意, 粉, ，, 搞, 两, 粒, 鸡, 蛋, ，, r, u, n, n...","親, 要, 食, 意, 粉, ，, 攪, 兩, 碌, 雞, 蛋, ，, r, a, i, n...",42,12,1,2,15,./audio/1289.wav
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,我個Favourite嘅band係‘BTS’，我每次聽佢地嘅歌曲都感覺好fresh，而且佢地...,我個 favourite 嘅 band 系 B T S，我每次聽佢哋啲歌曲都感覺好 fres...,0.3729,0.7273,0.3591,6.421,2.3061,"我個, Favourite, 嘅, band, 係‘, BTS, ’，我每次聽佢地嘅歌曲都感...","我個, favourite, 嘅, band, 系, B, T, S, ，我每次聽佢哋啲歌曲...",...,0,8,"我, 個, F, a, v, o, u, r, i, t, e, 嘅, b, a, n, d...","我, 個, , f, a, v, o, u, r, i, t, e, , 嘅, , b...",59,9,6,7,22,./audio/765.wav
496,496,無論讀幾多書，都係experience會教曬你，唔好怕explore新嘅地方和了解新嘅事物。,無論讀幾多書，都係experience會教授你，唔好派 explore 新嘅地方同埋了解新嘅事物。,0.1304,0.4000,0.2935,5.909,1.7346,"無論讀幾多書，都係, experience, 會教曬你，唔好怕, explore, 新嘅地方...","無論讀幾多書，都係, experience, 會教授你，唔好派, explore, 新嘅地方...",...,0,2,"無, 論, 讀, 幾, 多, 書, ，, 都, 係, e, x, p, e, r, i, e...","無, 論, 讀, 幾, 多, 書, ，, 都, 係, e, x, p, e, r, i, e...",46,3,0,3,6,./audio/1356.wav
497,497,我哋嘅長者搵唔到工作，政府需要提供更多支援，包括job training programs。,我哋嘅長者揾唔到工作，政府需要提供更多支援，包括job training programmes。,0.0652,0.4000,0.2555,5.461,1.3953,"我哋嘅長者搵唔到工作，政府需要提供更多支援，包括, job, training, progr...","我哋嘅長者揾唔到工作，政府需要提供更多支援，包括, job, training, progr...",...,0,2,"我, 哋, 嘅, 長, 者, 搵, 唔, 到, 工, 作, ，, 政, 府, 需, 要, 提...","我, 哋, 嘅, 長, 者, 揾, 唔, 到, 工, 作, ，, 政, 府, 需, 要, 提...",46,1,0,2,3,./audio/408.wav
498,498,去Central嘅IFC買Burberry嘅新款手袋，sales話佢地仲有折扣呢!,去 central 嘅 IFC，買 Burberry 嘅新款手袋， sell 話佢哋仲有折扣呢～,0.3171,0.4444,0.1304,13.355,1.7409,"去, Central, 嘅, IFC, 買, Burberry, 嘅新款手袋，, sales...","去, central, 嘅, IFC, ，買, Burberry, 嘅新款手袋，, sell...",...,0,4,"去, C, e, n, t, r, a, l, 嘅, I, F, C, 買, B, u, r...","去, , c, e, n, t, r, a, l, , 嘅, , I, F, C, ，...",41,6,0,7,13,./audio/1614.wav
499,499,香港教育制度需要讓學生擁有more comprehensive skill sets，以應對...,香港教育制度需要讓學生擁有more concepts skills，以應對未來社會嘅挑戰。,0.2407,0.5000,0.2083,5.973,1.2443,"香港教育制度需要讓學生擁有, more, comprehensive, skill, set...","香港教育制度需要讓學生擁有, more, concepts, skills, ，以應對未來社...",...,0,3,"香, 港, 教, 育, 制, 度, 需, 要, 讓, 學, 生, 擁, 有, m, o, r...","香, 港, 教, 育, 制, 度, 需, 要, 讓, 學, 生, 擁, 有, m, o, r...",54,4,9,0,13,./audio/694.wav

In [83]:
playAudio(evalResultDF.iloc[6]["audio"])
print(evalResultDF.iloc[6]["ref_words_array"])
print(evalResultDF.iloc[6]["pred_words_array"])

最近迷上飲, green, tea, latte, ，一, sec, 係清新嘅, green, tea, 味，下一, sec, 又係, milky, creamy, textures, ，真係好, enjoy, !
最近迷想飲, Green, Tea, 綠, tea, 一塞係色新嘅, Green, Tea, 味，下一塞又係, Milky, Creamy, Texture, ，可真係好人中意。

In [84]:
evalResultDF.iloc[6]

index                                                                 6
ref_text              最近迷上飲green tea latte，一sec係清新嘅green tea味，下一sec又...
pred_text             最近迷想飲Green Tea綠tea一塞係色新嘅Green Tea味，下一塞又係Milky ...
cer                                                               0.359
wer                                                              0.9444
rtf                                                              0.2774
audio_duration_sec                                                7.765
inference_time_sec                                               2.1538
ref_words_array       最近迷上飲, green, tea, latte, ，一, sec, 係清新嘅, green...
pred_words_array      最近迷想飲, Green, Tea, 綠, tea, 一塞係色新嘅, Green, Tea,...
ref_words                                                            18
wer_substitutions                                                    12
wer_deletions                                                         5
wer_insertions                                                        0
wer_errors_(S+D+I)                                                   17
ref_chars_array       最, 近, 迷, 上, 飲, g, r, e, e, n,  , t, e, a,  , l...
pred_chars_array      最, 近, 迷, 想, 飲, G, r, e, e, n,  , T, e, a, 綠, t...
ref_chars                                                            78
cer_substitutions                                                    19
cer_deletions                                                         9
cer_insertions                                                        0
cer_errors_(S+D+I)                                                   28
audio                                                   ./audio/938.wav
Name: 6, dtype: object